// GENERATED by tools/gen-node-defs — do not edit.
// Source: nodes/Wiring/loader.go struct tags + nodes/<Kind>/<Kind>.go.
//
// This module describes the keys that Go's loader reads from topology.json.
// View-only fields (position, edge midpointOffset, UI labels not in loader.go)
// are intentionally absent — they are validated by hand in TS.

// Top-level node fields read by the Go loader.
export interface TopoNode {
  id: string;
  type: string;          // PascalCase Go kind
  data?: Record<string, unknown>; // per-kind data blob (loader reads wire:"data.*" fields)
  edgeSeeds?: Record<string, number>; // pre-sent values for ring topologies
}

// Top-level edge fields read by the Go loader.
export interface TopoEdge {
  id: string;
  source: string;
  target: string;
  sourceHandle: string;
  targetHandle: string;
  label: string;         // channel name in the substrate
}

// Valid edgeSeeds keys per Go kind (input port names).
// Derived from *Wiring.In fields — same source as REQUIRED_INPUTS in node-defs.ts.
export const EDGE_SEED_PORTS: Record<string, string[]> = {
  "ChainInhibitor":    ["FromPrevChainInhibitorNode"],
  "InhibitRightGate":  ["FromLeft", "FromRight"],
  "ReadGate":          ["FromInput", "FromChainInhibitor"],
};
