// Code generated by tools/gen-kind-imports. DO NOT EDIT.

package main

import (
	_ "github.com/dtauraso/wirefold/nodes/excitatory"
	_ "github.com/dtauraso/wirefold/nodes/holdflip"
	_ "github.com/dtauraso/wirefold/nodes/inhibitor"
	_ "github.com/dtauraso/wirefold/nodes/input"
	_ "github.com/dtauraso/wirefold/nodes/windowandgate"
)
