// GENERATED by tools/gen-node-defs — do not edit.
// Source: Buffer/layout.go  Regenerate: cd tools/topology-vscode && npm run gen:node-defs
// BUF_LAYOUT_FINGERPRINT: version:13|block:Bead[X:f32:0,Y:f32:4,Z:f32:8,Value:i32:12,Frac:f32:16,BeadID:u32:20,Live:u8:24]:stride:25|block:Node[CX:f32:0,CY:f32:4,CZ:f32:8,Radius:f32:12,SphereR:f32:16,VRX:f32:20,VRY:f32:24,VRZ:f32:28,FRX:f32:32,FRY:f32:36,FRZ:f32:40,TorusRed:u8:44,MissVal:i32:45,MX:f32:49,MY:f32:53,MZ:f32:57,EvRecv:u8:61,EvFire:u8:62,EvSend:u8:63,EvArrive:u8:64,EvDone:u8:65,Selected:u8:66,KindId:u8:67,LabelOff:u32:68,LabelLen:u32:72,Faded:u8:76,Hovered:u8:77]:stride:78|block:Interior[Present:u8:0,Value:i32:1,OX:f32:5,OY:f32:9,OZ:f32:13]:stride:17|block:Edge[SX:f32:0,SY:f32:4,SZ:f32:8,EX:f32:12,EY:f32:16,EZ:f32:20,SrcNodeRow:i32:24,DstNodeRow:i32:28,Selected:u8:32,Faded:u8:33,EdgeLabelOff:u32:34,EdgeLabelLen:u32:38]:stride:42|block:Port[NodeRow:i32:0,DX:f32:4,DY:f32:8,DZ:f32:12,IsInput:u8:16,Hovered:u8:17,PortNameOff:u32:18,PortNameLen:u32:22]:stride:26|block:Camera[PX:f32:0,PY:f32:4,PZ:f32:8,R:f32:12,PosTheta:f32:16,PosPhi:f32:20,UpTheta:f32:24,UpPhi:f32:28]:stride:32|block:Overlay[SceneTori:u8:0,ScenePoles:u8:1,NodePoles:u8:2,AngleLabels:u8:3,SelSpherePoles:u8:4,Handholds:u8:5,LabelsGlobal:u8:6,BadgesGlobal:u8:7,OverlaysVis:u8:8,DoubleLinks:u8:9,SelMode:u8:10]:stride:11|block:Event[Kind:u8:0,NodeRow:i32:1,PortRow:i32:5,TargetRow:i32:9,TargetPortRow:i32:13,EdgeRow:i32:17,Slot:i32:21,Value:i32:25,Bead:u32:29,ArcLength:f32:33,SimLatencyMs:f32:37,X:f32:41,Y:f32:45,Z:f32:49,F:f32:53]:stride:57|event[Recv:0,Fire:1,Send:2,Arrive:3,Done:4]

package Buffer

import (
	"encoding/binary"
	"math"
)

// BufLayoutVersionGenerated must equal BufLayoutVersion in layout.go.
const BufLayoutVersionGenerated = 13

// BufHeaderSize is the byte width of the snapshot header:
// [tick:u32][beadCount:u32][nodeCount:u32][edgeCount:u32][portCount:u32][labelBytesCount:u32][eventCount:u32][portNameBytesCount:u32][edgeLabelBytesCount:u32]
const BufHeaderSize = 36

// ── Bead block ───────────────────────────────────────────────
const (
	BufBeadColX      = 0  // f32
	BufBeadColY      = 4  // f32
	BufBeadColZ      = 8  // f32
	BufBeadColValue  = 12 // i32
	BufBeadColFrac   = 16 // f32
	BufBeadColBeadID = 20 // u32
	BufBeadColLive   = 24 // u8
	BufBeadStride    = 25
)

// SetBeadRow writes one Bead row into buf[row*BufBeadStride:].
func SetBeadRow(buf []byte, row int, x float32, y float32, z float32, value int32, frac float32, beadID uint32, live uint8) {
	off := row * BufBeadStride
	binary.LittleEndian.PutUint32(buf[off+0:], math.Float32bits(x))
	binary.LittleEndian.PutUint32(buf[off+4:], math.Float32bits(y))
	binary.LittleEndian.PutUint32(buf[off+8:], math.Float32bits(z))
	binary.LittleEndian.PutUint32(buf[off+12:], uint32(value))
	binary.LittleEndian.PutUint32(buf[off+16:], math.Float32bits(frac))
	binary.LittleEndian.PutUint32(buf[off+20:], beadID)
	buf[off+24] = live
}

// ── Node block ───────────────────────────────────────────────
const (
	BufNodeColCX       = 0  // f32
	BufNodeColCY       = 4  // f32
	BufNodeColCZ       = 8  // f32
	BufNodeColRadius   = 12 // f32
	BufNodeColSphereR  = 16 // f32
	BufNodeColVRX      = 20 // f32
	BufNodeColVRY      = 24 // f32
	BufNodeColVRZ      = 28 // f32
	BufNodeColFRX      = 32 // f32
	BufNodeColFRY      = 36 // f32
	BufNodeColFRZ      = 40 // f32
	BufNodeColTorusRed = 44 // u8
	BufNodeColMissVal  = 45 // i32
	BufNodeColMX       = 49 // f32
	BufNodeColMY       = 53 // f32
	BufNodeColMZ       = 57 // f32
	BufNodeColEvRecv   = 61 // u8
	BufNodeColEvFire   = 62 // u8
	BufNodeColEvSend   = 63 // u8
	BufNodeColEvArrive = 64 // u8
	BufNodeColEvDone   = 65 // u8
	BufNodeColSelected = 66 // u8
	BufNodeColKindId   = 67 // u8
	BufNodeColLabelOff = 68 // u32
	BufNodeColLabelLen = 72 // u32
	BufNodeColFaded    = 76 // u8
	BufNodeColHovered  = 77 // u8
	BufNodeStride      = 78
)

// SetNodeRow writes one Node row into buf[row*BufNodeStride:].
func SetNodeRow(buf []byte, row int, cX float32, cY float32, cZ float32, radius float32, sphereR float32, vRX float32, vRY float32, vRZ float32, fRX float32, fRY float32, fRZ float32, torusRed uint8, missVal int32, mX float32, mY float32, mZ float32, evRecv uint8, evFire uint8, evSend uint8, evArrive uint8, evDone uint8, selected uint8, kindId uint8, labelOff uint32, labelLen uint32, faded uint8, hovered uint8) {
	off := row * BufNodeStride
	binary.LittleEndian.PutUint32(buf[off+0:], math.Float32bits(cX))
	binary.LittleEndian.PutUint32(buf[off+4:], math.Float32bits(cY))
	binary.LittleEndian.PutUint32(buf[off+8:], math.Float32bits(cZ))
	binary.LittleEndian.PutUint32(buf[off+12:], math.Float32bits(radius))
	binary.LittleEndian.PutUint32(buf[off+16:], math.Float32bits(sphereR))
	binary.LittleEndian.PutUint32(buf[off+20:], math.Float32bits(vRX))
	binary.LittleEndian.PutUint32(buf[off+24:], math.Float32bits(vRY))
	binary.LittleEndian.PutUint32(buf[off+28:], math.Float32bits(vRZ))
	binary.LittleEndian.PutUint32(buf[off+32:], math.Float32bits(fRX))
	binary.LittleEndian.PutUint32(buf[off+36:], math.Float32bits(fRY))
	binary.LittleEndian.PutUint32(buf[off+40:], math.Float32bits(fRZ))
	buf[off+44] = torusRed
	binary.LittleEndian.PutUint32(buf[off+45:], uint32(missVal))
	binary.LittleEndian.PutUint32(buf[off+49:], math.Float32bits(mX))
	binary.LittleEndian.PutUint32(buf[off+53:], math.Float32bits(mY))
	binary.LittleEndian.PutUint32(buf[off+57:], math.Float32bits(mZ))
	buf[off+61] = evRecv
	buf[off+62] = evFire
	buf[off+63] = evSend
	buf[off+64] = evArrive
	buf[off+65] = evDone
	buf[off+66] = selected
	buf[off+67] = kindId
	binary.LittleEndian.PutUint32(buf[off+68:], labelOff)
	binary.LittleEndian.PutUint32(buf[off+72:], labelLen)
	buf[off+76] = faded
	buf[off+77] = hovered
}

// ── Interior block ───────────────────────────────────────────
const (
	BufInteriorColPresent = 0  // u8
	BufInteriorColValue   = 1  // i32
	BufInteriorColOX      = 5  // f32
	BufInteriorColOY      = 9  // f32
	BufInteriorColOZ      = 13 // f32
	BufInteriorStride     = 17
)

// SetInteriorRow writes one Interior row into buf[row*BufInteriorStride:].
func SetInteriorRow(buf []byte, row int, present uint8, value int32, oX float32, oY float32, oZ float32) {
	off := row * BufInteriorStride
	buf[off+0] = present
	binary.LittleEndian.PutUint32(buf[off+1:], uint32(value))
	binary.LittleEndian.PutUint32(buf[off+5:], math.Float32bits(oX))
	binary.LittleEndian.PutUint32(buf[off+9:], math.Float32bits(oY))
	binary.LittleEndian.PutUint32(buf[off+13:], math.Float32bits(oZ))
}

// ── Edge block ───────────────────────────────────────────────
const (
	BufEdgeColSX           = 0  // f32
	BufEdgeColSY           = 4  // f32
	BufEdgeColSZ           = 8  // f32
	BufEdgeColEX           = 12 // f32
	BufEdgeColEY           = 16 // f32
	BufEdgeColEZ           = 20 // f32
	BufEdgeColSrcNodeRow   = 24 // i32
	BufEdgeColDstNodeRow   = 28 // i32
	BufEdgeColSelected     = 32 // u8
	BufEdgeColFaded        = 33 // u8
	BufEdgeColEdgeLabelOff = 34 // u32
	BufEdgeColEdgeLabelLen = 38 // u32
	BufEdgeStride          = 42
)

// SetEdgeRow writes one Edge row into buf[row*BufEdgeStride:].
func SetEdgeRow(buf []byte, row int, sX float32, sY float32, sZ float32, eX float32, eY float32, eZ float32, srcNodeRow int32, dstNodeRow int32, selected uint8, faded uint8, edgeLabelOff uint32, edgeLabelLen uint32) {
	off := row * BufEdgeStride
	binary.LittleEndian.PutUint32(buf[off+0:], math.Float32bits(sX))
	binary.LittleEndian.PutUint32(buf[off+4:], math.Float32bits(sY))
	binary.LittleEndian.PutUint32(buf[off+8:], math.Float32bits(sZ))
	binary.LittleEndian.PutUint32(buf[off+12:], math.Float32bits(eX))
	binary.LittleEndian.PutUint32(buf[off+16:], math.Float32bits(eY))
	binary.LittleEndian.PutUint32(buf[off+20:], math.Float32bits(eZ))
	binary.LittleEndian.PutUint32(buf[off+24:], uint32(srcNodeRow))
	binary.LittleEndian.PutUint32(buf[off+28:], uint32(dstNodeRow))
	buf[off+32] = selected
	buf[off+33] = faded
	binary.LittleEndian.PutUint32(buf[off+34:], edgeLabelOff)
	binary.LittleEndian.PutUint32(buf[off+38:], edgeLabelLen)
}

// ── Port block ───────────────────────────────────────────────
const (
	BufPortColNodeRow     = 0  // i32
	BufPortColDX          = 4  // f32
	BufPortColDY          = 8  // f32
	BufPortColDZ          = 12 // f32
	BufPortColIsInput     = 16 // u8
	BufPortColHovered     = 17 // u8
	BufPortColPortNameOff = 18 // u32
	BufPortColPortNameLen = 22 // u32
	BufPortStride         = 26
)

// SetPortRow writes one Port row into buf[row*BufPortStride:].
func SetPortRow(buf []byte, row int, nodeRow int32, dX float32, dY float32, dZ float32, isInput uint8, hovered uint8, portNameOff uint32, portNameLen uint32) {
	off := row * BufPortStride
	binary.LittleEndian.PutUint32(buf[off+0:], uint32(nodeRow))
	binary.LittleEndian.PutUint32(buf[off+4:], math.Float32bits(dX))
	binary.LittleEndian.PutUint32(buf[off+8:], math.Float32bits(dY))
	binary.LittleEndian.PutUint32(buf[off+12:], math.Float32bits(dZ))
	buf[off+16] = isInput
	buf[off+17] = hovered
	binary.LittleEndian.PutUint32(buf[off+18:], portNameOff)
	binary.LittleEndian.PutUint32(buf[off+22:], portNameLen)
}

// ── Camera block ─────────────────────────────────────────────
const (
	BufCameraColPX       = 0  // f32
	BufCameraColPY       = 4  // f32
	BufCameraColPZ       = 8  // f32
	BufCameraColR        = 12 // f32
	BufCameraColPosTheta = 16 // f32
	BufCameraColPosPhi   = 20 // f32
	BufCameraColUpTheta  = 24 // f32
	BufCameraColUpPhi    = 28 // f32
	BufCameraStride      = 32
)

// SetCameraRow writes the Camera row into buf (always 1 row; no row param).
func SetCameraRow(buf []byte, pX float32, pY float32, pZ float32, r float32, posTheta float32, posPhi float32, upTheta float32, upPhi float32) {
	binary.LittleEndian.PutUint32(buf[0:], math.Float32bits(pX))
	binary.LittleEndian.PutUint32(buf[4:], math.Float32bits(pY))
	binary.LittleEndian.PutUint32(buf[8:], math.Float32bits(pZ))
	binary.LittleEndian.PutUint32(buf[12:], math.Float32bits(r))
	binary.LittleEndian.PutUint32(buf[16:], math.Float32bits(posTheta))
	binary.LittleEndian.PutUint32(buf[20:], math.Float32bits(posPhi))
	binary.LittleEndian.PutUint32(buf[24:], math.Float32bits(upTheta))
	binary.LittleEndian.PutUint32(buf[28:], math.Float32bits(upPhi))
}

// ── Overlay block ────────────────────────────────────────────
const (
	BufOverlayColSceneTori      = 0  // u8
	BufOverlayColScenePoles     = 1  // u8
	BufOverlayColNodePoles      = 2  // u8
	BufOverlayColAngleLabels    = 3  // u8
	BufOverlayColSelSpherePoles = 4  // u8
	BufOverlayColHandholds      = 5  // u8
	BufOverlayColLabelsGlobal   = 6  // u8
	BufOverlayColBadgesGlobal   = 7  // u8
	BufOverlayColOverlaysVis    = 8  // u8
	BufOverlayColDoubleLinks    = 9  // u8
	BufOverlayColSelMode        = 10 // u8
	BufOverlayStride            = 11
)

// SetOverlayRow writes the Overlay row into buf (always 1 row; no row param).
func SetOverlayRow(buf []byte, sceneTori uint8, scenePoles uint8, nodePoles uint8, angleLabels uint8, selSpherePoles uint8, handholds uint8, labelsGlobal uint8, badgesGlobal uint8, overlaysVis uint8, doubleLinks uint8, selMode uint8) {
	buf[0] = sceneTori
	buf[1] = scenePoles
	buf[2] = nodePoles
	buf[3] = angleLabels
	buf[4] = selSpherePoles
	buf[5] = handholds
	buf[6] = labelsGlobal
	buf[7] = badgesGlobal
	buf[8] = overlaysVis
	buf[9] = doubleLinks
	buf[10] = selMode
}

// ── Event block ──────────────────────────────────────────────
const (
	BufEventColKind          = 0  // u8
	BufEventColNodeRow       = 1  // i32
	BufEventColPortRow       = 5  // i32
	BufEventColTargetRow     = 9  // i32
	BufEventColTargetPortRow = 13 // i32
	BufEventColEdgeRow       = 17 // i32
	BufEventColSlot          = 21 // i32
	BufEventColValue         = 25 // i32
	BufEventColBead          = 29 // u32
	BufEventColArcLength     = 33 // f32
	BufEventColSimLatencyMs  = 37 // f32
	BufEventColX             = 41 // f32
	BufEventColY             = 45 // f32
	BufEventColZ             = 49 // f32
	BufEventColF             = 53 // f32
	BufEventStride           = 57
)

// SetEventRow writes one Event row into buf[row*BufEventStride:].
func SetEventRow(buf []byte, row int, kind uint8, nodeRow int32, portRow int32, targetRow int32, targetPortRow int32, edgeRow int32, slot int32, value int32, bead uint32, arcLength float32, simLatencyMs float32, x float32, y float32, z float32, f float32) {
	off := row * BufEventStride
	buf[off+0] = kind
	binary.LittleEndian.PutUint32(buf[off+1:], uint32(nodeRow))
	binary.LittleEndian.PutUint32(buf[off+5:], uint32(portRow))
	binary.LittleEndian.PutUint32(buf[off+9:], uint32(targetRow))
	binary.LittleEndian.PutUint32(buf[off+13:], uint32(targetPortRow))
	binary.LittleEndian.PutUint32(buf[off+17:], uint32(edgeRow))
	binary.LittleEndian.PutUint32(buf[off+21:], uint32(slot))
	binary.LittleEndian.PutUint32(buf[off+25:], uint32(value))
	binary.LittleEndian.PutUint32(buf[off+29:], bead)
	binary.LittleEndian.PutUint32(buf[off+33:], math.Float32bits(arcLength))
	binary.LittleEndian.PutUint32(buf[off+37:], math.Float32bits(simLatencyMs))
	binary.LittleEndian.PutUint32(buf[off+41:], math.Float32bits(x))
	binary.LittleEndian.PutUint32(buf[off+45:], math.Float32bits(y))
	binary.LittleEndian.PutUint32(buf[off+49:], math.Float32bits(z))
	binary.LittleEndian.PutUint32(buf[off+53:], math.Float32bits(f))
}

// ── Semantic event enum ─────────────────────────────────────────────────────────
// Transient per-node flags stored in node rows (EvRecv/EvFire/…).
// These ids are embedded in snapshots; names are resolved from this schema.
const (
	BufEventRecvID   = 0
	BufEventFireID   = 1
	BufEventSendID   = 2
	BufEventArriveID = 3
	BufEventDoneID   = 4
)
