// GENERATED by tools/gen-node-defs — do not edit.
// Source: Buffer/layout.go  Regenerate: cd tools/topology-vscode && npm run gen:node-defs
// BUF_LAYOUT_FINGERPRINT: version:5|block:Bead[X:f32:0,Y:f32:4,Z:f32:8,Value:i32:12,Frac:f32:16,BeadID:u32:20,Live:u8:24]:stride:25|block:Node[CX:f32:0,CY:f32:4,CZ:f32:8,Radius:f32:12,SphereR:f32:16,TorusRed:u8:20,MissVal:i32:21,MX:f32:25,MY:f32:29,MZ:f32:33,EvRecv:u8:37,EvFire:u8:38,EvSend:u8:39,EvArrive:u8:40,EvDone:u8:41,Selected:u8:42]:stride:43|block:Interior[Present:u8:0,Value:i32:1,OX:f32:5,OY:f32:9,OZ:f32:13]:stride:17|block:Edge[SX:f32:0,SY:f32:4,SZ:f32:8,EX:f32:12,EY:f32:16,EZ:f32:20,SrcNodeRow:i32:24,DstNodeRow:i32:28]:stride:32|block:Camera[PX:f32:0,PY:f32:4,PZ:f32:8,R:f32:12,PosTheta:f32:16,PosPhi:f32:20,UpTheta:f32:24,UpPhi:f32:28]:stride:32|block:Overlay[SceneTori:u8:0,ScenePoles:u8:1,NodePoles:u8:2,AngleLabels:u8:3,SelSpherePoles:u8:4,Handholds:u8:5,LabelsGlobal:u8:6,BadgesGlobal:u8:7,OverlaysVis:u8:8,DoubleLinks:u8:9,SelMode:u8:10]:stride:11|event[Recv:0,Fire:1,Send:2,Arrive:3,Done:4]

package Buffer

import (
	"encoding/binary"
	"math"
)

// BufLayoutVersionGenerated must equal BufLayoutVersion in layout.go.
const BufLayoutVersionGenerated = 5

// BufHeaderSize is the byte width of the snapshot header:
// [tick:u32][beadCount:u32][nodeCount:u32][edgeCount:u32]
const BufHeaderSize = 16

// ── Bead block ───────────────────────────────────────────────
const (
	BufBeadColX      = 0  // f32
	BufBeadColY      = 4  // f32
	BufBeadColZ      = 8  // f32
	BufBeadColValue  = 12 // i32
	BufBeadColFrac   = 16 // f32
	BufBeadColBeadID = 20 // u32
	BufBeadColLive   = 24 // u8
	BufBeadStride    = 25
)

// SetBeadRow writes one Bead row into buf[row*BufBeadStride:].
func SetBeadRow(buf []byte, row int, x float32, y float32, z float32, value int32, frac float32, beadID uint32, live uint8) {
	off := row * BufBeadStride
	binary.LittleEndian.PutUint32(buf[off+0:], math.Float32bits(x))
	binary.LittleEndian.PutUint32(buf[off+4:], math.Float32bits(y))
	binary.LittleEndian.PutUint32(buf[off+8:], math.Float32bits(z))
	binary.LittleEndian.PutUint32(buf[off+12:], uint32(value))
	binary.LittleEndian.PutUint32(buf[off+16:], math.Float32bits(frac))
	binary.LittleEndian.PutUint32(buf[off+20:], beadID)
	buf[off+24] = live
}

// ── Node block ───────────────────────────────────────────────
const (
	BufNodeColCX       = 0  // f32
	BufNodeColCY       = 4  // f32
	BufNodeColCZ       = 8  // f32
	BufNodeColRadius   = 12 // f32
	BufNodeColSphereR  = 16 // f32
	BufNodeColTorusRed = 20 // u8
	BufNodeColMissVal  = 21 // i32
	BufNodeColMX       = 25 // f32
	BufNodeColMY       = 29 // f32
	BufNodeColMZ       = 33 // f32
	BufNodeColEvRecv   = 37 // u8
	BufNodeColEvFire   = 38 // u8
	BufNodeColEvSend   = 39 // u8
	BufNodeColEvArrive = 40 // u8
	BufNodeColEvDone   = 41 // u8
	BufNodeColSelected = 42 // u8
	BufNodeStride      = 43
)

// SetNodeRow writes one Node row into buf[row*BufNodeStride:].
func SetNodeRow(buf []byte, row int, cX float32, cY float32, cZ float32, radius float32, sphereR float32, torusRed uint8, missVal int32, mX float32, mY float32, mZ float32, evRecv uint8, evFire uint8, evSend uint8, evArrive uint8, evDone uint8, selected uint8) {
	off := row * BufNodeStride
	binary.LittleEndian.PutUint32(buf[off+0:], math.Float32bits(cX))
	binary.LittleEndian.PutUint32(buf[off+4:], math.Float32bits(cY))
	binary.LittleEndian.PutUint32(buf[off+8:], math.Float32bits(cZ))
	binary.LittleEndian.PutUint32(buf[off+12:], math.Float32bits(radius))
	binary.LittleEndian.PutUint32(buf[off+16:], math.Float32bits(sphereR))
	buf[off+20] = torusRed
	binary.LittleEndian.PutUint32(buf[off+21:], uint32(missVal))
	binary.LittleEndian.PutUint32(buf[off+25:], math.Float32bits(mX))
	binary.LittleEndian.PutUint32(buf[off+29:], math.Float32bits(mY))
	binary.LittleEndian.PutUint32(buf[off+33:], math.Float32bits(mZ))
	buf[off+37] = evRecv
	buf[off+38] = evFire
	buf[off+39] = evSend
	buf[off+40] = evArrive
	buf[off+41] = evDone
	buf[off+42] = selected
}

// ── Interior block ───────────────────────────────────────────
const (
	BufInteriorColPresent = 0  // u8
	BufInteriorColValue   = 1  // i32
	BufInteriorColOX      = 5  // f32
	BufInteriorColOY      = 9  // f32
	BufInteriorColOZ      = 13 // f32
	BufInteriorStride     = 17
)

// SetInteriorRow writes one Interior row into buf[row*BufInteriorStride:].
func SetInteriorRow(buf []byte, row int, present uint8, value int32, oX float32, oY float32, oZ float32) {
	off := row * BufInteriorStride
	buf[off+0] = present
	binary.LittleEndian.PutUint32(buf[off+1:], uint32(value))
	binary.LittleEndian.PutUint32(buf[off+5:], math.Float32bits(oX))
	binary.LittleEndian.PutUint32(buf[off+9:], math.Float32bits(oY))
	binary.LittleEndian.PutUint32(buf[off+13:], math.Float32bits(oZ))
}

// ── Edge block ───────────────────────────────────────────────
const (
	BufEdgeColSX         = 0  // f32
	BufEdgeColSY         = 4  // f32
	BufEdgeColSZ         = 8  // f32
	BufEdgeColEX         = 12 // f32
	BufEdgeColEY         = 16 // f32
	BufEdgeColEZ         = 20 // f32
	BufEdgeColSrcNodeRow = 24 // i32
	BufEdgeColDstNodeRow = 28 // i32
	BufEdgeStride        = 32
)

// SetEdgeRow writes one Edge row into buf[row*BufEdgeStride:].
func SetEdgeRow(buf []byte, row int, sX float32, sY float32, sZ float32, eX float32, eY float32, eZ float32, srcNodeRow int32, dstNodeRow int32) {
	off := row * BufEdgeStride
	binary.LittleEndian.PutUint32(buf[off+0:], math.Float32bits(sX))
	binary.LittleEndian.PutUint32(buf[off+4:], math.Float32bits(sY))
	binary.LittleEndian.PutUint32(buf[off+8:], math.Float32bits(sZ))
	binary.LittleEndian.PutUint32(buf[off+12:], math.Float32bits(eX))
	binary.LittleEndian.PutUint32(buf[off+16:], math.Float32bits(eY))
	binary.LittleEndian.PutUint32(buf[off+20:], math.Float32bits(eZ))
	binary.LittleEndian.PutUint32(buf[off+24:], uint32(srcNodeRow))
	binary.LittleEndian.PutUint32(buf[off+28:], uint32(dstNodeRow))
}

// ── Camera block ─────────────────────────────────────────────
const (
	BufCameraColPX       = 0  // f32
	BufCameraColPY       = 4  // f32
	BufCameraColPZ       = 8  // f32
	BufCameraColR        = 12 // f32
	BufCameraColPosTheta = 16 // f32
	BufCameraColPosPhi   = 20 // f32
	BufCameraColUpTheta  = 24 // f32
	BufCameraColUpPhi    = 28 // f32
	BufCameraStride      = 32
)

// SetCameraRow writes the Camera row into buf (always 1 row; no row param).
func SetCameraRow(buf []byte, pX float32, pY float32, pZ float32, r float32, posTheta float32, posPhi float32, upTheta float32, upPhi float32) {
	binary.LittleEndian.PutUint32(buf[0:], math.Float32bits(pX))
	binary.LittleEndian.PutUint32(buf[4:], math.Float32bits(pY))
	binary.LittleEndian.PutUint32(buf[8:], math.Float32bits(pZ))
	binary.LittleEndian.PutUint32(buf[12:], math.Float32bits(r))
	binary.LittleEndian.PutUint32(buf[16:], math.Float32bits(posTheta))
	binary.LittleEndian.PutUint32(buf[20:], math.Float32bits(posPhi))
	binary.LittleEndian.PutUint32(buf[24:], math.Float32bits(upTheta))
	binary.LittleEndian.PutUint32(buf[28:], math.Float32bits(upPhi))
}

// ── Overlay block ────────────────────────────────────────────
const (
	BufOverlayColSceneTori      = 0  // u8
	BufOverlayColScenePoles     = 1  // u8
	BufOverlayColNodePoles      = 2  // u8
	BufOverlayColAngleLabels    = 3  // u8
	BufOverlayColSelSpherePoles = 4  // u8
	BufOverlayColHandholds      = 5  // u8
	BufOverlayColLabelsGlobal   = 6  // u8
	BufOverlayColBadgesGlobal   = 7  // u8
	BufOverlayColOverlaysVis    = 8  // u8
	BufOverlayColDoubleLinks    = 9  // u8
	BufOverlayColSelMode        = 10 // u8
	BufOverlayStride            = 11
)

// SetOverlayRow writes the Overlay row into buf (always 1 row; no row param).
func SetOverlayRow(buf []byte, sceneTori uint8, scenePoles uint8, nodePoles uint8, angleLabels uint8, selSpherePoles uint8, handholds uint8, labelsGlobal uint8, badgesGlobal uint8, overlaysVis uint8, doubleLinks uint8, selMode uint8) {
	buf[0] = sceneTori
	buf[1] = scenePoles
	buf[2] = nodePoles
	buf[3] = angleLabels
	buf[4] = selSpherePoles
	buf[5] = handholds
	buf[6] = labelsGlobal
	buf[7] = badgesGlobal
	buf[8] = overlaysVis
	buf[9] = doubleLinks
	buf[10] = selMode
}

// ── Semantic event enum ─────────────────────────────────────────────────────────
// Transient per-node flags stored in node rows (EvRecv/EvFire/…).
// These ids are embedded in snapshots; names are resolved from this schema.
const (
	BufEventRecvID   = 0
	BufEventFireID   = 1
	BufEventSendID   = 2
	BufEventArriveID = 3
	BufEventDoneID   = 4
)
