// GENERATED by tools/gen-node-defs — do not edit.
// Source: Buffer/layout.go  Regenerate: cd tools/topology-vscode && npm run gen:node-defs
// BUF_LAYOUT_FINGERPRINT: version:33|interiorSlotsPerNode:4|block:Bead[X:f32:0,Y:f32:4,Z:f32:8,Value:i32:12,Live:u8:16]:stride:17|block:Node[CX:f32:0,CY:f32:4,CZ:f32:8,Radius:f32:12,SphereR:f32:16,VRX:f32:20,VRY:f32:24,VRZ:f32:28,FRX:f32:32,FRY:f32:36,FRZ:f32:40,Selected:u8:44,KindId:u8:45,LabelOff:u32:46,LabelLen:u32:50,Hovered:u8:54,LatchedSel:u8:55,GotDragMsg:u8:56,DragDeltaA:i32:57,DragDeltaB:i32:61,DragDeltaC:i32:65]:stride:69|block:Interior[Present:u8:0,Value:i32:1,OX:f32:5,OY:f32:9,OZ:f32:13]:stride:17|block:Edge[SrcPortRow:i32:0,DstPortRow:i32:4,Selected:u8:8,EdgeLabelOff:u32:9,EdgeLabelLen:u32:13]:stride:17|block:LayoutLink[SrcNodeRow:i32:0,DstNodeRow:i32:4,EdgeRow:i32:8]:stride:12|block:Port[NodeRow:i32:0,DX:f32:4,DY:f32:8,DZ:f32:12,PX:f32:16,PY:f32:20,PZ:f32:24,IsInput:u8:28,Hovered:u8:29,PortNameOff:u32:30,PortNameLen:u32:34]:stride:38|block:Camera[PX:f32:0,PY:f32:4,PZ:f32:8,R:f32:12,PosTheta:f32:16,PosPhi:f32:20,UpTheta:f32:24,UpPhi:f32:28]:stride:32|block:Overlay[SceneTori:u8:0,ScenePoles:u8:1,NodePoles:u8:2,SelSpherePoles:u8:3,Handholds:u8:4,LabelsGlobal:u8:5,OverlaysVis:u8:6,DoubleLinks:u8:7,AbcDragCount:u32:8]:stride:12|block:Scene[CX:f32:0,CY:f32:4,CZ:f32:8,Radius:f32:12]:stride:16|block:Event[Kind:u8:0,NodeRow:i32:1,PortRow:i32:5,TargetRow:i32:9,TargetPortRow:i32:13,EdgeRow:i32:17,Slot:i32:21,Value:i32:25,Bead:u32:29,ArcLength:f32:33,SimLatencyMs:f32:37,X:f32:41,Y:f32:45,Z:f32:49,F:f32:53,Label:u8:57,Debug:u8:58,TextOff:u32:59,TextLen:u32:63]:stride:67

package Buffer

import (
	"encoding/binary"
	"math"
)

// BufLayoutVersionGenerated must equal BufLayoutVersion in layout.go.
const BufLayoutVersionGenerated = 33

// BufInteriorSlotsPerNodeGenerated must equal BufInteriorSlotsPerNode in layout.go.
const BufInteriorSlotsPerNodeGenerated = 4

// BufHeaderSize is the byte width of the SCENE frame's snapshot header. The Bead block
// (see BufBeadHeaderSize), the Node/Interior/Port blocks + Label/PortName bytes (see
// BufNodeFrameHeaderSize), and the Edge block + edge-label bytes (see
// BufEdgeFrameHeaderSize) are their own tagged frames — Buffer/frame_tags.go — so the
// SCENE header no longer carries their counts. The EVENT block was also RETIRED from
// this frame (memory/feedback_no_single_writer_bridge.md — each per-owner stream now
// carries its own trailing EVENTS section instead):
// [tick:u32][layoutLinkCount:u32]
const BufHeaderSize = 8

// ── Bead block ───────────────────────────────────────────────
const (
	BufBeadColX     = 0  // f32
	BufBeadColY     = 4  // f32
	BufBeadColZ     = 8  // f32
	BufBeadColValue = 12 // i32
	BufBeadColLive  = 16 // u8
	BufBeadStride   = 17
)

// SetBeadRow writes one Bead row into buf[row*BufBeadStride:].
func SetBeadRow(buf []byte, row int, x float32, y float32, z float32, value int32, live uint8) {
	off := row * BufBeadStride
	binary.LittleEndian.PutUint32(buf[off+0:], math.Float32bits(x))
	binary.LittleEndian.PutUint32(buf[off+4:], math.Float32bits(y))
	binary.LittleEndian.PutUint32(buf[off+8:], math.Float32bits(z))
	binary.LittleEndian.PutUint32(buf[off+12:], uint32(value))
	buf[off+16] = live
}

// ── Node block ───────────────────────────────────────────────
const (
	BufNodeColCX         = 0  // f32
	BufNodeColCY         = 4  // f32
	BufNodeColCZ         = 8  // f32
	BufNodeColRadius     = 12 // f32
	BufNodeColSphereR    = 16 // f32
	BufNodeColVRX        = 20 // f32
	BufNodeColVRY        = 24 // f32
	BufNodeColVRZ        = 28 // f32
	BufNodeColFRX        = 32 // f32
	BufNodeColFRY        = 36 // f32
	BufNodeColFRZ        = 40 // f32
	BufNodeColSelected   = 44 // u8
	BufNodeColKindId     = 45 // u8
	BufNodeColLabelOff   = 46 // u32
	BufNodeColLabelLen   = 50 // u32
	BufNodeColHovered    = 54 // u8
	BufNodeColLatchedSel = 55 // u8
	BufNodeColGotDragMsg = 56 // u8
	BufNodeColDragDeltaA = 57 // i32
	BufNodeColDragDeltaB = 61 // i32
	BufNodeColDragDeltaC = 65 // i32
	BufNodeStride        = 69
)

// SetNodeRow writes one Node row into buf[row*BufNodeStride:].
func SetNodeRow(buf []byte, row int, cX float32, cY float32, cZ float32, radius float32, sphereR float32, vRX float32, vRY float32, vRZ float32, fRX float32, fRY float32, fRZ float32, selected uint8, kindId uint8, labelOff uint32, labelLen uint32, hovered uint8, latchedSel uint8, gotDragMsg uint8, dragDeltaA int32, dragDeltaB int32, dragDeltaC int32) {
	off := row * BufNodeStride
	binary.LittleEndian.PutUint32(buf[off+0:], math.Float32bits(cX))
	binary.LittleEndian.PutUint32(buf[off+4:], math.Float32bits(cY))
	binary.LittleEndian.PutUint32(buf[off+8:], math.Float32bits(cZ))
	binary.LittleEndian.PutUint32(buf[off+12:], math.Float32bits(radius))
	binary.LittleEndian.PutUint32(buf[off+16:], math.Float32bits(sphereR))
	binary.LittleEndian.PutUint32(buf[off+20:], math.Float32bits(vRX))
	binary.LittleEndian.PutUint32(buf[off+24:], math.Float32bits(vRY))
	binary.LittleEndian.PutUint32(buf[off+28:], math.Float32bits(vRZ))
	binary.LittleEndian.PutUint32(buf[off+32:], math.Float32bits(fRX))
	binary.LittleEndian.PutUint32(buf[off+36:], math.Float32bits(fRY))
	binary.LittleEndian.PutUint32(buf[off+40:], math.Float32bits(fRZ))
	buf[off+44] = selected
	buf[off+45] = kindId
	binary.LittleEndian.PutUint32(buf[off+46:], labelOff)
	binary.LittleEndian.PutUint32(buf[off+50:], labelLen)
	buf[off+54] = hovered
	buf[off+55] = latchedSel
	buf[off+56] = gotDragMsg
	binary.LittleEndian.PutUint32(buf[off+57:], uint32(dragDeltaA))
	binary.LittleEndian.PutUint32(buf[off+61:], uint32(dragDeltaB))
	binary.LittleEndian.PutUint32(buf[off+65:], uint32(dragDeltaC))
}

// ── Interior block ───────────────────────────────────────────
const (
	BufInteriorColPresent = 0  // u8
	BufInteriorColValue   = 1  // i32
	BufInteriorColOX      = 5  // f32
	BufInteriorColOY      = 9  // f32
	BufInteriorColOZ      = 13 // f32
	BufInteriorStride     = 17
)

// SetInteriorRow writes one Interior row into buf[row*BufInteriorStride:].
func SetInteriorRow(buf []byte, row int, present uint8, value int32, oX float32, oY float32, oZ float32) {
	off := row * BufInteriorStride
	buf[off+0] = present
	binary.LittleEndian.PutUint32(buf[off+1:], uint32(value))
	binary.LittleEndian.PutUint32(buf[off+5:], math.Float32bits(oX))
	binary.LittleEndian.PutUint32(buf[off+9:], math.Float32bits(oY))
	binary.LittleEndian.PutUint32(buf[off+13:], math.Float32bits(oZ))
}

// ── Edge block ───────────────────────────────────────────────
const (
	BufEdgeColSrcPortRow   = 0  // i32
	BufEdgeColDstPortRow   = 4  // i32
	BufEdgeColSelected     = 8  // u8
	BufEdgeColEdgeLabelOff = 9  // u32
	BufEdgeColEdgeLabelLen = 13 // u32
	BufEdgeStride          = 17
)

// SetEdgeRow writes one Edge row into buf[row*BufEdgeStride:].
func SetEdgeRow(buf []byte, row int, srcPortRow int32, dstPortRow int32, selected uint8, edgeLabelOff uint32, edgeLabelLen uint32) {
	off := row * BufEdgeStride
	binary.LittleEndian.PutUint32(buf[off+0:], uint32(srcPortRow))
	binary.LittleEndian.PutUint32(buf[off+4:], uint32(dstPortRow))
	buf[off+8] = selected
	binary.LittleEndian.PutUint32(buf[off+9:], edgeLabelOff)
	binary.LittleEndian.PutUint32(buf[off+13:], edgeLabelLen)
}

// ── LayoutLink block ─────────────────────────────────────────
const (
	BufLayoutLinkColSrcNodeRow = 0 // i32
	BufLayoutLinkColDstNodeRow = 4 // i32
	BufLayoutLinkColEdgeRow    = 8 // i32
	BufLayoutLinkStride        = 12
)

// SetLayoutLinkRow writes one LayoutLink row into buf[row*BufLayoutLinkStride:].
func SetLayoutLinkRow(buf []byte, row int, srcNodeRow int32, dstNodeRow int32, edgeRow int32) {
	off := row * BufLayoutLinkStride
	binary.LittleEndian.PutUint32(buf[off+0:], uint32(srcNodeRow))
	binary.LittleEndian.PutUint32(buf[off+4:], uint32(dstNodeRow))
	binary.LittleEndian.PutUint32(buf[off+8:], uint32(edgeRow))
}

// ── Port block ───────────────────────────────────────────────
const (
	BufPortColNodeRow     = 0  // i32
	BufPortColDX          = 4  // f32
	BufPortColDY          = 8  // f32
	BufPortColDZ          = 12 // f32
	BufPortColPX          = 16 // f32
	BufPortColPY          = 20 // f32
	BufPortColPZ          = 24 // f32
	BufPortColIsInput     = 28 // u8
	BufPortColHovered     = 29 // u8
	BufPortColPortNameOff = 30 // u32
	BufPortColPortNameLen = 34 // u32
	BufPortStride         = 38
)

// SetPortRow writes one Port row into buf[row*BufPortStride:].
func SetPortRow(buf []byte, row int, nodeRow int32, dX float32, dY float32, dZ float32, pX float32, pY float32, pZ float32, isInput uint8, hovered uint8, portNameOff uint32, portNameLen uint32) {
	off := row * BufPortStride
	binary.LittleEndian.PutUint32(buf[off+0:], uint32(nodeRow))
	binary.LittleEndian.PutUint32(buf[off+4:], math.Float32bits(dX))
	binary.LittleEndian.PutUint32(buf[off+8:], math.Float32bits(dY))
	binary.LittleEndian.PutUint32(buf[off+12:], math.Float32bits(dZ))
	binary.LittleEndian.PutUint32(buf[off+16:], math.Float32bits(pX))
	binary.LittleEndian.PutUint32(buf[off+20:], math.Float32bits(pY))
	binary.LittleEndian.PutUint32(buf[off+24:], math.Float32bits(pZ))
	buf[off+28] = isInput
	buf[off+29] = hovered
	binary.LittleEndian.PutUint32(buf[off+30:], portNameOff)
	binary.LittleEndian.PutUint32(buf[off+34:], portNameLen)
}

// ── Camera block ─────────────────────────────────────────────
const (
	BufCameraColPX       = 0  // f32
	BufCameraColPY       = 4  // f32
	BufCameraColPZ       = 8  // f32
	BufCameraColR        = 12 // f32
	BufCameraColPosTheta = 16 // f32
	BufCameraColPosPhi   = 20 // f32
	BufCameraColUpTheta  = 24 // f32
	BufCameraColUpPhi    = 28 // f32
	BufCameraStride      = 32
)

// SetCameraRow writes the Camera row into buf (always 1 row; no row param).
func SetCameraRow(buf []byte, pX float32, pY float32, pZ float32, r float32, posTheta float32, posPhi float32, upTheta float32, upPhi float32) {
	binary.LittleEndian.PutUint32(buf[0:], math.Float32bits(pX))
	binary.LittleEndian.PutUint32(buf[4:], math.Float32bits(pY))
	binary.LittleEndian.PutUint32(buf[8:], math.Float32bits(pZ))
	binary.LittleEndian.PutUint32(buf[12:], math.Float32bits(r))
	binary.LittleEndian.PutUint32(buf[16:], math.Float32bits(posTheta))
	binary.LittleEndian.PutUint32(buf[20:], math.Float32bits(posPhi))
	binary.LittleEndian.PutUint32(buf[24:], math.Float32bits(upTheta))
	binary.LittleEndian.PutUint32(buf[28:], math.Float32bits(upPhi))
}

// ── Overlay block ────────────────────────────────────────────
const (
	BufOverlayColSceneTori      = 0 // u8
	BufOverlayColScenePoles     = 1 // u8
	BufOverlayColNodePoles      = 2 // u8
	BufOverlayColSelSpherePoles = 3 // u8
	BufOverlayColHandholds      = 4 // u8
	BufOverlayColLabelsGlobal   = 5 // u8
	BufOverlayColOverlaysVis    = 6 // u8
	BufOverlayColDoubleLinks    = 7 // u8
	BufOverlayColAbcDragCount   = 8 // u32
	BufOverlayStride            = 12
)

// OverlayRow is the named-field snapshot of the Overlay block (single row).
// Passed BY VALUE to SetOverlayRow so the write call never enumerates fields
// positionally — closes the swapped-adjacent-uint8-args hazard a positional
// writer call would otherwise compile silently.
type OverlayRow struct {
	SceneTori      uint8
	ScenePoles     uint8
	NodePoles      uint8
	SelSpherePoles uint8
	Handholds      uint8
	LabelsGlobal   uint8
	OverlaysVis    uint8
	DoubleLinks    uint8
	AbcDragCount   uint32
}

// SetOverlayRow writes the Overlay row into buf (always 1 row; no row param).
func SetOverlayRow(buf []byte, row OverlayRow) {
	buf[0] = row.SceneTori
	buf[1] = row.ScenePoles
	buf[2] = row.NodePoles
	buf[3] = row.SelSpherePoles
	buf[4] = row.Handholds
	buf[5] = row.LabelsGlobal
	buf[6] = row.OverlaysVis
	buf[7] = row.DoubleLinks
	binary.LittleEndian.PutUint32(buf[8:], row.AbcDragCount)
}

// ── Scene block ──────────────────────────────────────────────
const (
	BufSceneColCX     = 0  // f32
	BufSceneColCY     = 4  // f32
	BufSceneColCZ     = 8  // f32
	BufSceneColRadius = 12 // f32
	BufSceneStride    = 16
)

// SetSceneRow writes the Scene row into buf (always 1 row; no row param).
func SetSceneRow(buf []byte, cX float32, cY float32, cZ float32, radius float32) {
	binary.LittleEndian.PutUint32(buf[0:], math.Float32bits(cX))
	binary.LittleEndian.PutUint32(buf[4:], math.Float32bits(cY))
	binary.LittleEndian.PutUint32(buf[8:], math.Float32bits(cZ))
	binary.LittleEndian.PutUint32(buf[12:], math.Float32bits(radius))
}

// ── Event block ──────────────────────────────────────────────
const (
	BufEventColKind          = 0  // u8
	BufEventColNodeRow       = 1  // i32
	BufEventColPortRow       = 5  // i32
	BufEventColTargetRow     = 9  // i32
	BufEventColTargetPortRow = 13 // i32
	BufEventColEdgeRow       = 17 // i32
	BufEventColSlot          = 21 // i32
	BufEventColValue         = 25 // i32
	BufEventColBead          = 29 // u32
	BufEventColArcLength     = 33 // f32
	BufEventColSimLatencyMs  = 37 // f32
	BufEventColX             = 41 // f32
	BufEventColY             = 45 // f32
	BufEventColZ             = 49 // f32
	BufEventColF             = 53 // f32
	BufEventColLabel         = 57 // u8
	BufEventColDebug         = 58 // u8
	BufEventColTextOff       = 59 // u32
	BufEventColTextLen       = 63 // u32
	BufEventStride           = 67
)

// SetEventRow writes one Event row into buf[row*BufEventStride:].
func SetEventRow(buf []byte, row int, kind uint8, nodeRow int32, portRow int32, targetRow int32, targetPortRow int32, edgeRow int32, slot int32, value int32, bead uint32, arcLength float32, simLatencyMs float32, x float32, y float32, z float32, f float32, label uint8, debug uint8, textOff uint32, textLen uint32) {
	off := row * BufEventStride
	buf[off+0] = kind
	binary.LittleEndian.PutUint32(buf[off+1:], uint32(nodeRow))
	binary.LittleEndian.PutUint32(buf[off+5:], uint32(portRow))
	binary.LittleEndian.PutUint32(buf[off+9:], uint32(targetRow))
	binary.LittleEndian.PutUint32(buf[off+13:], uint32(targetPortRow))
	binary.LittleEndian.PutUint32(buf[off+17:], uint32(edgeRow))
	binary.LittleEndian.PutUint32(buf[off+21:], uint32(slot))
	binary.LittleEndian.PutUint32(buf[off+25:], uint32(value))
	binary.LittleEndian.PutUint32(buf[off+29:], bead)
	binary.LittleEndian.PutUint32(buf[off+33:], math.Float32bits(arcLength))
	binary.LittleEndian.PutUint32(buf[off+37:], math.Float32bits(simLatencyMs))
	binary.LittleEndian.PutUint32(buf[off+41:], math.Float32bits(x))
	binary.LittleEndian.PutUint32(buf[off+45:], math.Float32bits(y))
	binary.LittleEndian.PutUint32(buf[off+49:], math.Float32bits(z))
	binary.LittleEndian.PutUint32(buf[off+53:], math.Float32bits(f))
	buf[off+57] = label
	buf[off+58] = debug
	binary.LittleEndian.PutUint32(buf[off+59:], textOff)
	binary.LittleEndian.PutUint32(buf[off+63:], textLen)
}
