// GENERATED by tools/gen-node-defs — do not edit.
// Source: nodes/<Kind>/SPEC.md + Wiring.Register calls.
// Regenerate with: cd tools/topology-vscode && npm run gen:node-defs

package Buffer

// KindIDUnknown is the sentinel KindId value when a node's kind is not in kindIDMap.
const KindIDUnknown uint8 = 0xFF

// kindIDMap maps a node's Go kind name (PascalCase) to its 0-based index
// in the alphabetically-sorted NODE_DEFS_ARRAY emitted by the same generator.
// Index i here ↔ NODE_DEFS_ARRAY[i] on the TS side.
var kindIDMap = map[string]uint8{
	"Hold":                      0,
	"HoldFlip":                  1,
	"HoldNewSendOld":            2,
	"Input":                     3,
	"Pacer":                     4,
	"Pulse":                     5,
	"WindowAndInhibitLeftGate":  6,
	"WindowAndInhibitRightGate": 7,
}

// NodeKindID returns the buffer KindId for a node's Go kind string.
// Returns KindIDUnknown (0xFF) when the kind is not in the registry.
func NodeKindID(kind string) uint8 {
	if id, ok := kindIDMap[kind]; ok {
		return id
	}
	return KindIDUnknown
}
