// GENERATED by tools/gen-node-defs — do not edit.
// Source: Buffer/layout.go  Regenerate: npm run gen:node-defs
// BUF_LAYOUT_FINGERPRINT: version:19|block:Bead[X:f32:0,Y:f32:4,Z:f32:8,Value:i32:12,Frac:f32:16,BeadID:u32:20,Live:u8:24]:stride:25|block:Node[CX:f32:0,CY:f32:4,CZ:f32:8,Radius:f32:12,SphereR:f32:16,VRX:f32:20,VRY:f32:24,VRZ:f32:28,FRX:f32:32,FRY:f32:36,FRZ:f32:40,EvRecv:u8:44,EvFire:u8:45,EvSend:u8:46,EvArrive:u8:47,EvDone:u8:48,Selected:u8:49,KindId:u8:50,LabelOff:u32:51,LabelLen:u32:55,Faded:u8:59,Hovered:u8:60]:stride:61|block:Interior[Present:u8:0,Value:i32:1,OX:f32:5,OY:f32:9,OZ:f32:13]:stride:17|block:Edge[SX:f32:0,SY:f32:4,SZ:f32:8,EX:f32:12,EY:f32:16,EZ:f32:20,SrcNodeRow:i32:24,DstNodeRow:i32:28,Selected:u8:32,Faded:u8:33,EdgeLabelOff:u32:34,EdgeLabelLen:u32:38]:stride:42|block:Port[NodeRow:i32:0,DX:f32:4,DY:f32:8,DZ:f32:12,PX:f32:16,PY:f32:20,PZ:f32:24,IsInput:u8:28,Hovered:u8:29,PortNameOff:u32:30,PortNameLen:u32:34]:stride:38|block:Camera[PX:f32:0,PY:f32:4,PZ:f32:8,R:f32:12,PosTheta:f32:16,PosPhi:f32:20,UpTheta:f32:24,UpPhi:f32:28]:stride:32|block:Overlay[SceneTori:u8:0,ScenePoles:u8:1,NodePoles:u8:2,AngleLabels:u8:3,SelSpherePoles:u8:4,Handholds:u8:5,LabelsGlobal:u8:6,BadgesGlobal:u8:7,OverlaysVis:u8:8,SelMode:u8:9]:stride:10|block:RuleBuilder[CenterRow:i32:0,PendingCode:u8:4,TermCount:u8:5,T0Row:i32:6,T0Code:u8:10,T1Row:i32:11,T1Code:u8:15,SelectedLockIndex:i32:16,PendingPortRow:i32:20,PendingPortIsInput:u8:24,PendingTorusRow:i32:25]:stride:29|block:PolarLock[CenterRow:i32:0,ARow:i32:4,ACode:u8:8,BRow:i32:9,BCode:u8:13,Active:u8:14,Kind:u8:15,PortRow:i32:16,PortIsInput:u8:20,TorusRow:i32:21,Selected:u8:25,Owned:u8:26]:stride:27|block:Event[Kind:u8:0,NodeRow:i32:1,PortRow:i32:5,TargetRow:i32:9,TargetPortRow:i32:13,EdgeRow:i32:17,Slot:i32:21,Value:i32:25,Bead:u32:29,ArcLength:f32:33,SimLatencyMs:f32:37,X:f32:41,Y:f32:45,Z:f32:49,F:f32:53]:stride:57|event[Recv:0,Fire:1,Send:2,Arrive:3,Done:4]

/** Schema version — must match BufLayoutVersion in Buffer/layout.go. */
export const BUF_LAYOUT_VERSION = 19;

/** Snapshot header: [tick:u32][beadCount:u32][nodeCount:u32][edgeCount:u32][portCount:u32][labelBytesCount:u32][eventCount:u32][portNameBytesCount:u32][edgeLabelBytesCount:u32][polarLockCount:u32] */
export const BUF_HEADER_SIZE = 40;

// ── Bead block ───────────────────────────────────────────────
export const BEAD_COL_X                          = 0; // f32
export const BEAD_COL_Y                          = 4; // f32
export const BEAD_COL_Z                          = 8; // f32
export const BEAD_COL_VALUE                      = 12; // i32
export const BEAD_COL_FRAC                       = 16; // f32
export const BEAD_COL_BEAD_ID                    = 20; // u32
export const BEAD_COL_LIVE                       = 24; // u8
export const BEAD_STRIDE                         = 25;

export function readBeadX(view: DataView, row: number): number { return view.getFloat32(row * BEAD_STRIDE + BEAD_COL_X, true); }
export function readBeadY(view: DataView, row: number): number { return view.getFloat32(row * BEAD_STRIDE + BEAD_COL_Y, true); }
export function readBeadZ(view: DataView, row: number): number { return view.getFloat32(row * BEAD_STRIDE + BEAD_COL_Z, true); }
export function readBeadValue(view: DataView, row: number): number { return view.getInt32(row * BEAD_STRIDE + BEAD_COL_VALUE, true); }
export function readBeadFrac(view: DataView, row: number): number { return view.getFloat32(row * BEAD_STRIDE + BEAD_COL_FRAC, true); }
export function readBeadBeadID(view: DataView, row: number): number { return view.getUint32(row * BEAD_STRIDE + BEAD_COL_BEAD_ID, true); }
export function readBeadLive(view: DataView, row: number): number { return view.getUint8(row * BEAD_STRIDE + BEAD_COL_LIVE); }

// ── Node block ───────────────────────────────────────────────
export const NODE_COL_CX                         = 0; // f32
export const NODE_COL_CY                         = 4; // f32
export const NODE_COL_CZ                         = 8; // f32
export const NODE_COL_RADIUS                     = 12; // f32
export const NODE_COL_SPHERE_R                   = 16; // f32
export const NODE_COL_VRX                        = 20; // f32
export const NODE_COL_VRY                        = 24; // f32
export const NODE_COL_VRZ                        = 28; // f32
export const NODE_COL_FRX                        = 32; // f32
export const NODE_COL_FRY                        = 36; // f32
export const NODE_COL_FRZ                        = 40; // f32
export const NODE_COL_EV_RECV                    = 44; // u8
export const NODE_COL_EV_FIRE                    = 45; // u8
export const NODE_COL_EV_SEND                    = 46; // u8
export const NODE_COL_EV_ARRIVE                  = 47; // u8
export const NODE_COL_EV_DONE                    = 48; // u8
export const NODE_COL_SELECTED                   = 49; // u8
export const NODE_COL_KIND_ID                    = 50; // u8
export const NODE_COL_LABEL_OFF                  = 51; // u32
export const NODE_COL_LABEL_LEN                  = 55; // u32
export const NODE_COL_FADED                      = 59; // u8
export const NODE_COL_HOVERED                    = 60; // u8
export const NODE_STRIDE                         = 61;

export function readNodeCX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CX, true); }
export function readNodeCY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CY, true); }
export function readNodeCZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CZ, true); }
export function readNodeRadius(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RADIUS, true); }
export function readNodeSphereR(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_SPHERE_R, true); }
export function readNodeVRX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_VRX, true); }
export function readNodeVRY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_VRY, true); }
export function readNodeVRZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_VRZ, true); }
export function readNodeFRX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_FRX, true); }
export function readNodeFRY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_FRY, true); }
export function readNodeFRZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_FRZ, true); }
export function readNodeEvRecv(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_EV_RECV); }
export function readNodeEvFire(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_EV_FIRE); }
export function readNodeEvSend(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_EV_SEND); }
export function readNodeEvArrive(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_EV_ARRIVE); }
export function readNodeEvDone(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_EV_DONE); }
export function readNodeSelected(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_SELECTED); }
export function readNodeKindId(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_KIND_ID); }
export function readNodeLabelOff(view: DataView, row: number): number { return view.getUint32(row * NODE_STRIDE + NODE_COL_LABEL_OFF, true); }
export function readNodeLabelLen(view: DataView, row: number): number { return view.getUint32(row * NODE_STRIDE + NODE_COL_LABEL_LEN, true); }
export function readNodeFaded(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_FADED); }
export function readNodeHovered(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_HOVERED); }

// ── Interior block ───────────────────────────────────────────
export const INTERIOR_COL_PRESENT                = 0; // u8
export const INTERIOR_COL_VALUE                  = 1; // i32
export const INTERIOR_COL_OX                     = 5; // f32
export const INTERIOR_COL_OY                     = 9; // f32
export const INTERIOR_COL_OZ                     = 13; // f32
export const INTERIOR_STRIDE                     = 17;

export function readInteriorPresent(view: DataView, row: number): number { return view.getUint8(row * INTERIOR_STRIDE + INTERIOR_COL_PRESENT); }
export function readInteriorValue(view: DataView, row: number): number { return view.getInt32(row * INTERIOR_STRIDE + INTERIOR_COL_VALUE, true); }
export function readInteriorOX(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_OX, true); }
export function readInteriorOY(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_OY, true); }
export function readInteriorOZ(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_OZ, true); }

// ── Edge block ───────────────────────────────────────────────
export const EDGE_COL_SX                         = 0; // f32
export const EDGE_COL_SY                         = 4; // f32
export const EDGE_COL_SZ                         = 8; // f32
export const EDGE_COL_EX                         = 12; // f32
export const EDGE_COL_EY                         = 16; // f32
export const EDGE_COL_EZ                         = 20; // f32
export const EDGE_COL_SRC_NODE_ROW               = 24; // i32
export const EDGE_COL_DST_NODE_ROW               = 28; // i32
export const EDGE_COL_SELECTED                   = 32; // u8
export const EDGE_COL_FADED                      = 33; // u8
export const EDGE_COL_EDGE_LABEL_OFF             = 34; // u32
export const EDGE_COL_EDGE_LABEL_LEN             = 38; // u32
export const EDGE_STRIDE                         = 42;

export function readEdgeSX(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_SX, true); }
export function readEdgeSY(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_SY, true); }
export function readEdgeSZ(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_SZ, true); }
export function readEdgeEX(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_EX, true); }
export function readEdgeEY(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_EY, true); }
export function readEdgeEZ(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_EZ, true); }
export function readEdgeSrcNodeRow(view: DataView, row: number): number { return view.getInt32(row * EDGE_STRIDE + EDGE_COL_SRC_NODE_ROW, true); }
export function readEdgeDstNodeRow(view: DataView, row: number): number { return view.getInt32(row * EDGE_STRIDE + EDGE_COL_DST_NODE_ROW, true); }
export function readEdgeSelected(view: DataView, row: number): number { return view.getUint8(row * EDGE_STRIDE + EDGE_COL_SELECTED); }
export function readEdgeFaded(view: DataView, row: number): number { return view.getUint8(row * EDGE_STRIDE + EDGE_COL_FADED); }
export function readEdgeEdgeLabelOff(view: DataView, row: number): number { return view.getUint32(row * EDGE_STRIDE + EDGE_COL_EDGE_LABEL_OFF, true); }
export function readEdgeEdgeLabelLen(view: DataView, row: number): number { return view.getUint32(row * EDGE_STRIDE + EDGE_COL_EDGE_LABEL_LEN, true); }

// ── Port block ───────────────────────────────────────────────
export const PORT_COL_NODE_ROW                   = 0; // i32
export const PORT_COL_DX                         = 4; // f32
export const PORT_COL_DY                         = 8; // f32
export const PORT_COL_DZ                         = 12; // f32
export const PORT_COL_PX                         = 16; // f32
export const PORT_COL_PY                         = 20; // f32
export const PORT_COL_PZ                         = 24; // f32
export const PORT_COL_IS_INPUT                   = 28; // u8
export const PORT_COL_HOVERED                    = 29; // u8
export const PORT_COL_PORT_NAME_OFF              = 30; // u32
export const PORT_COL_PORT_NAME_LEN              = 34; // u32
export const PORT_STRIDE                         = 38;

export function readPortNodeRow(view: DataView, row: number): number { return view.getInt32(row * PORT_STRIDE + PORT_COL_NODE_ROW, true); }
export function readPortDX(view: DataView, row: number): number { return view.getFloat32(row * PORT_STRIDE + PORT_COL_DX, true); }
export function readPortDY(view: DataView, row: number): number { return view.getFloat32(row * PORT_STRIDE + PORT_COL_DY, true); }
export function readPortDZ(view: DataView, row: number): number { return view.getFloat32(row * PORT_STRIDE + PORT_COL_DZ, true); }
export function readPortPX(view: DataView, row: number): number { return view.getFloat32(row * PORT_STRIDE + PORT_COL_PX, true); }
export function readPortPY(view: DataView, row: number): number { return view.getFloat32(row * PORT_STRIDE + PORT_COL_PY, true); }
export function readPortPZ(view: DataView, row: number): number { return view.getFloat32(row * PORT_STRIDE + PORT_COL_PZ, true); }
export function readPortIsInput(view: DataView, row: number): number { return view.getUint8(row * PORT_STRIDE + PORT_COL_IS_INPUT); }
export function readPortHovered(view: DataView, row: number): number { return view.getUint8(row * PORT_STRIDE + PORT_COL_HOVERED); }
export function readPortPortNameOff(view: DataView, row: number): number { return view.getUint32(row * PORT_STRIDE + PORT_COL_PORT_NAME_OFF, true); }
export function readPortPortNameLen(view: DataView, row: number): number { return view.getUint32(row * PORT_STRIDE + PORT_COL_PORT_NAME_LEN, true); }

// ── Camera block ─────────────────────────────────────────────
export const CAMERA_COL_PX                       = 0; // f32
export const CAMERA_COL_PY                       = 4; // f32
export const CAMERA_COL_PZ                       = 8; // f32
export const CAMERA_COL_R                        = 12; // f32
export const CAMERA_COL_POS_THETA                = 16; // f32
export const CAMERA_COL_POS_PHI                  = 20; // f32
export const CAMERA_COL_UP_THETA                 = 24; // f32
export const CAMERA_COL_UP_PHI                   = 28; // f32
export const CAMERA_STRIDE                       = 32;

export function readCameraPX(view: DataView): number { return view.getFloat32(CAMERA_COL_PX, true); }
export function readCameraPY(view: DataView): number { return view.getFloat32(CAMERA_COL_PY, true); }
export function readCameraPZ(view: DataView): number { return view.getFloat32(CAMERA_COL_PZ, true); }
export function readCameraR(view: DataView): number { return view.getFloat32(CAMERA_COL_R, true); }
export function readCameraPosTheta(view: DataView): number { return view.getFloat32(CAMERA_COL_POS_THETA, true); }
export function readCameraPosPhi(view: DataView): number { return view.getFloat32(CAMERA_COL_POS_PHI, true); }
export function readCameraUpTheta(view: DataView): number { return view.getFloat32(CAMERA_COL_UP_THETA, true); }
export function readCameraUpPhi(view: DataView): number { return view.getFloat32(CAMERA_COL_UP_PHI, true); }

// ── Overlay block ────────────────────────────────────────────
export const OVERLAY_COL_SCENE_TORI              = 0; // u8
export const OVERLAY_COL_SCENE_POLES             = 1; // u8
export const OVERLAY_COL_NODE_POLES              = 2; // u8
export const OVERLAY_COL_ANGLE_LABELS            = 3; // u8
export const OVERLAY_COL_SEL_SPHERE_POLES        = 4; // u8
export const OVERLAY_COL_HANDHOLDS               = 5; // u8
export const OVERLAY_COL_LABELS_GLOBAL           = 6; // u8
export const OVERLAY_COL_BADGES_GLOBAL           = 7; // u8
export const OVERLAY_COL_OVERLAYS_VIS            = 8; // u8
export const OVERLAY_COL_SEL_MODE                = 9; // u8
export const OVERLAY_STRIDE                      = 10;

export function readOverlaySceneTori(view: DataView): number { return view.getUint8(OVERLAY_COL_SCENE_TORI); }
export function readOverlayScenePoles(view: DataView): number { return view.getUint8(OVERLAY_COL_SCENE_POLES); }
export function readOverlayNodePoles(view: DataView): number { return view.getUint8(OVERLAY_COL_NODE_POLES); }
export function readOverlayAngleLabels(view: DataView): number { return view.getUint8(OVERLAY_COL_ANGLE_LABELS); }
export function readOverlaySelSpherePoles(view: DataView): number { return view.getUint8(OVERLAY_COL_SEL_SPHERE_POLES); }
export function readOverlayHandholds(view: DataView): number { return view.getUint8(OVERLAY_COL_HANDHOLDS); }
export function readOverlayLabelsGlobal(view: DataView): number { return view.getUint8(OVERLAY_COL_LABELS_GLOBAL); }
export function readOverlayBadgesGlobal(view: DataView): number { return view.getUint8(OVERLAY_COL_BADGES_GLOBAL); }
export function readOverlayOverlaysVis(view: DataView): number { return view.getUint8(OVERLAY_COL_OVERLAYS_VIS); }
export function readOverlaySelMode(view: DataView): number { return view.getUint8(OVERLAY_COL_SEL_MODE); }

// ── RuleBuilder block ────────────────────────────────────────
export const RULE_BUILDER_COL_CENTER_ROW         = 0; // i32
export const RULE_BUILDER_COL_PENDING_CODE       = 4; // u8
export const RULE_BUILDER_COL_TERM_COUNT         = 5; // u8
export const RULE_BUILDER_COL_T0ROW              = 6; // i32
export const RULE_BUILDER_COL_T0CODE             = 10; // u8
export const RULE_BUILDER_COL_T1ROW              = 11; // i32
export const RULE_BUILDER_COL_T1CODE             = 15; // u8
export const RULE_BUILDER_COL_SELECTED_LOCK_INDEX = 16; // i32
export const RULE_BUILDER_COL_PENDING_PORT_ROW   = 20; // i32
export const RULE_BUILDER_COL_PENDING_PORT_IS_INPUT = 24; // u8
export const RULE_BUILDER_COL_PENDING_TORUS_ROW  = 25; // i32
export const RULE_BUILDER_STRIDE                 = 29;

export function readRuleBuilderCenterRow(view: DataView): number { return view.getInt32(RULE_BUILDER_COL_CENTER_ROW, true); }
export function readRuleBuilderPendingCode(view: DataView): number { return view.getUint8(RULE_BUILDER_COL_PENDING_CODE); }
export function readRuleBuilderTermCount(view: DataView): number { return view.getUint8(RULE_BUILDER_COL_TERM_COUNT); }
export function readRuleBuilderT0Row(view: DataView): number { return view.getInt32(RULE_BUILDER_COL_T0ROW, true); }
export function readRuleBuilderT0Code(view: DataView): number { return view.getUint8(RULE_BUILDER_COL_T0CODE); }
export function readRuleBuilderT1Row(view: DataView): number { return view.getInt32(RULE_BUILDER_COL_T1ROW, true); }
export function readRuleBuilderT1Code(view: DataView): number { return view.getUint8(RULE_BUILDER_COL_T1CODE); }
export function readRuleBuilderSelectedLockIndex(view: DataView): number { return view.getInt32(RULE_BUILDER_COL_SELECTED_LOCK_INDEX, true); }
export function readRuleBuilderPendingPortRow(view: DataView): number { return view.getInt32(RULE_BUILDER_COL_PENDING_PORT_ROW, true); }
export function readRuleBuilderPendingPortIsInput(view: DataView): number { return view.getUint8(RULE_BUILDER_COL_PENDING_PORT_IS_INPUT); }
export function readRuleBuilderPendingTorusRow(view: DataView): number { return view.getInt32(RULE_BUILDER_COL_PENDING_TORUS_ROW, true); }

// ── PolarLock block ──────────────────────────────────────────
export const POLAR_LOCK_COL_CENTER_ROW           = 0; // i32
export const POLAR_LOCK_COL_AROW                 = 4; // i32
export const POLAR_LOCK_COL_ACODE                = 8; // u8
export const POLAR_LOCK_COL_BROW                 = 9; // i32
export const POLAR_LOCK_COL_BCODE                = 13; // u8
export const POLAR_LOCK_COL_ACTIVE               = 14; // u8
export const POLAR_LOCK_COL_KIND                 = 15; // u8
export const POLAR_LOCK_COL_PORT_ROW             = 16; // i32
export const POLAR_LOCK_COL_PORT_IS_INPUT        = 20; // u8
export const POLAR_LOCK_COL_TORUS_ROW            = 21; // i32
export const POLAR_LOCK_COL_SELECTED             = 25; // u8
export const POLAR_LOCK_COL_OWNED                = 26; // u8
export const POLAR_LOCK_STRIDE                   = 27;

export function readPolarLockCenterRow(view: DataView, row: number): number { return view.getInt32(row * POLAR_LOCK_STRIDE + POLAR_LOCK_COL_CENTER_ROW, true); }
export function readPolarLockARow(view: DataView, row: number): number { return view.getInt32(row * POLAR_LOCK_STRIDE + POLAR_LOCK_COL_AROW, true); }
export function readPolarLockACode(view: DataView, row: number): number { return view.getUint8(row * POLAR_LOCK_STRIDE + POLAR_LOCK_COL_ACODE); }
export function readPolarLockBRow(view: DataView, row: number): number { return view.getInt32(row * POLAR_LOCK_STRIDE + POLAR_LOCK_COL_BROW, true); }
export function readPolarLockBCode(view: DataView, row: number): number { return view.getUint8(row * POLAR_LOCK_STRIDE + POLAR_LOCK_COL_BCODE); }
export function readPolarLockActive(view: DataView, row: number): number { return view.getUint8(row * POLAR_LOCK_STRIDE + POLAR_LOCK_COL_ACTIVE); }
export function readPolarLockKind(view: DataView, row: number): number { return view.getUint8(row * POLAR_LOCK_STRIDE + POLAR_LOCK_COL_KIND); }
export function readPolarLockPortRow(view: DataView, row: number): number { return view.getInt32(row * POLAR_LOCK_STRIDE + POLAR_LOCK_COL_PORT_ROW, true); }
export function readPolarLockPortIsInput(view: DataView, row: number): number { return view.getUint8(row * POLAR_LOCK_STRIDE + POLAR_LOCK_COL_PORT_IS_INPUT); }
export function readPolarLockTorusRow(view: DataView, row: number): number { return view.getInt32(row * POLAR_LOCK_STRIDE + POLAR_LOCK_COL_TORUS_ROW, true); }
export function readPolarLockSelected(view: DataView, row: number): number { return view.getUint8(row * POLAR_LOCK_STRIDE + POLAR_LOCK_COL_SELECTED); }
export function readPolarLockOwned(view: DataView, row: number): number { return view.getUint8(row * POLAR_LOCK_STRIDE + POLAR_LOCK_COL_OWNED); }

// ── Event block ──────────────────────────────────────────────
export const EVENT_COL_KIND                      = 0; // u8
export const EVENT_COL_NODE_ROW                  = 1; // i32
export const EVENT_COL_PORT_ROW                  = 5; // i32
export const EVENT_COL_TARGET_ROW                = 9; // i32
export const EVENT_COL_TARGET_PORT_ROW           = 13; // i32
export const EVENT_COL_EDGE_ROW                  = 17; // i32
export const EVENT_COL_SLOT                      = 21; // i32
export const EVENT_COL_VALUE                     = 25; // i32
export const EVENT_COL_BEAD                      = 29; // u32
export const EVENT_COL_ARC_LENGTH                = 33; // f32
export const EVENT_COL_SIM_LATENCY_MS            = 37; // f32
export const EVENT_COL_X                         = 41; // f32
export const EVENT_COL_Y                         = 45; // f32
export const EVENT_COL_Z                         = 49; // f32
export const EVENT_COL_F                         = 53; // f32
export const EVENT_STRIDE                        = 57;

export function readEventKind(view: DataView, row: number): number { return view.getUint8(row * EVENT_STRIDE + EVENT_COL_KIND); }
export function readEventNodeRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_NODE_ROW, true); }
export function readEventPortRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_PORT_ROW, true); }
export function readEventTargetRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_TARGET_ROW, true); }
export function readEventTargetPortRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_TARGET_PORT_ROW, true); }
export function readEventEdgeRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_EDGE_ROW, true); }
export function readEventSlot(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_SLOT, true); }
export function readEventValue(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_VALUE, true); }
export function readEventBead(view: DataView, row: number): number { return view.getUint32(row * EVENT_STRIDE + EVENT_COL_BEAD, true); }
export function readEventArcLength(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_ARC_LENGTH, true); }
export function readEventSimLatencyMs(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_SIM_LATENCY_MS, true); }
export function readEventX(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_X, true); }
export function readEventY(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_Y, true); }
export function readEventZ(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_Z, true); }
export function readEventF(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_F, true); }

// ── Semantic event enum ─────────────────────────────────────────────────────────
// Transient per-node event flags; ids embedded in snapshots, names in this schema.
export const BUF_EVENT_RECV            = 0;
export const BUF_EVENT_FIRE            = 1;
export const BUF_EVENT_SEND            = 2;
export const BUF_EVENT_ARRIVE          = 3;
export const BUF_EVENT_DONE            = 4;
