// GENERATED by tools/gen-node-defs — do not edit.
// Source: Buffer/layout.go  Regenerate: npm run gen:node-defs
// BUF_LAYOUT_FINGERPRINT: version:13|block:Bead[X:f32:0,Y:f32:4,Z:f32:8,Value:i32:12,Frac:f32:16,BeadID:u32:20,Live:u8:24]:stride:25|block:Node[CX:f32:0,CY:f32:4,CZ:f32:8,Radius:f32:12,SphereR:f32:16,VRX:f32:20,VRY:f32:24,VRZ:f32:28,FRX:f32:32,FRY:f32:36,FRZ:f32:40,TorusRed:u8:44,MissVal:i32:45,MX:f32:49,MY:f32:53,MZ:f32:57,EvRecv:u8:61,EvFire:u8:62,EvSend:u8:63,EvArrive:u8:64,EvDone:u8:65,Selected:u8:66,KindId:u8:67,LabelOff:u32:68,LabelLen:u32:72,Faded:u8:76,Hovered:u8:77]:stride:78|block:Interior[Present:u8:0,Value:i32:1,OX:f32:5,OY:f32:9,OZ:f32:13]:stride:17|block:Edge[SX:f32:0,SY:f32:4,SZ:f32:8,EX:f32:12,EY:f32:16,EZ:f32:20,SrcNodeRow:i32:24,DstNodeRow:i32:28,Selected:u8:32,Faded:u8:33,EdgeLabelOff:u32:34,EdgeLabelLen:u32:38]:stride:42|block:Port[NodeRow:i32:0,DX:f32:4,DY:f32:8,DZ:f32:12,IsInput:u8:16,Hovered:u8:17,PortNameOff:u32:18,PortNameLen:u32:22]:stride:26|block:Camera[PX:f32:0,PY:f32:4,PZ:f32:8,R:f32:12,PosTheta:f32:16,PosPhi:f32:20,UpTheta:f32:24,UpPhi:f32:28]:stride:32|block:Overlay[SceneTori:u8:0,ScenePoles:u8:1,NodePoles:u8:2,AngleLabels:u8:3,SelSpherePoles:u8:4,Handholds:u8:5,LabelsGlobal:u8:6,BadgesGlobal:u8:7,OverlaysVis:u8:8,DoubleLinks:u8:9,SelMode:u8:10]:stride:11|block:Event[Kind:u8:0,NodeRow:i32:1,PortRow:i32:5,TargetRow:i32:9,TargetPortRow:i32:13,EdgeRow:i32:17,Slot:i32:21,Value:i32:25,Bead:u32:29,ArcLength:f32:33,SimLatencyMs:f32:37,X:f32:41,Y:f32:45,Z:f32:49,F:f32:53]:stride:57|event[Recv:0,Fire:1,Send:2,Arrive:3,Done:4]

/** Schema version — must match BufLayoutVersion in Buffer/layout.go. */
export const BUF_LAYOUT_VERSION = 13;

/** Snapshot header: [tick:u32][beadCount:u32][nodeCount:u32][edgeCount:u32][portCount:u32][labelBytesCount:u32][eventCount:u32][portNameBytesCount:u32][edgeLabelBytesCount:u32] */
export const BUF_HEADER_SIZE = 36;

// ── Bead block ───────────────────────────────────────────────
export const BEAD_COL_X                          = 0; // f32
export const BEAD_COL_Y                          = 4; // f32
export const BEAD_COL_Z                          = 8; // f32
export const BEAD_COL_VALUE                      = 12; // i32
export const BEAD_COL_FRAC                       = 16; // f32
export const BEAD_COL_BEAD_ID                    = 20; // u32
export const BEAD_COL_LIVE                       = 24; // u8
export const BEAD_STRIDE                         = 25;

export function readBeadX(view: DataView, row: number): number { return view.getFloat32(row * BEAD_STRIDE + BEAD_COL_X, true); }
export function readBeadY(view: DataView, row: number): number { return view.getFloat32(row * BEAD_STRIDE + BEAD_COL_Y, true); }
export function readBeadZ(view: DataView, row: number): number { return view.getFloat32(row * BEAD_STRIDE + BEAD_COL_Z, true); }
export function readBeadValue(view: DataView, row: number): number { return view.getInt32(row * BEAD_STRIDE + BEAD_COL_VALUE, true); }
export function readBeadFrac(view: DataView, row: number): number { return view.getFloat32(row * BEAD_STRIDE + BEAD_COL_FRAC, true); }
export function readBeadBeadID(view: DataView, row: number): number { return view.getUint32(row * BEAD_STRIDE + BEAD_COL_BEAD_ID, true); }
export function readBeadLive(view: DataView, row: number): number { return view.getUint8(row * BEAD_STRIDE + BEAD_COL_LIVE); }

// ── Node block ───────────────────────────────────────────────
export const NODE_COL_CX                         = 0; // f32
export const NODE_COL_CY                         = 4; // f32
export const NODE_COL_CZ                         = 8; // f32
export const NODE_COL_RADIUS                     = 12; // f32
export const NODE_COL_SPHERE_R                   = 16; // f32
export const NODE_COL_VRX                        = 20; // f32
export const NODE_COL_VRY                        = 24; // f32
export const NODE_COL_VRZ                        = 28; // f32
export const NODE_COL_FRX                        = 32; // f32
export const NODE_COL_FRY                        = 36; // f32
export const NODE_COL_FRZ                        = 40; // f32
export const NODE_COL_TORUS_RED                  = 44; // u8
export const NODE_COL_MISS_VAL                   = 45; // i32
export const NODE_COL_MX                         = 49; // f32
export const NODE_COL_MY                         = 53; // f32
export const NODE_COL_MZ                         = 57; // f32
export const NODE_COL_EV_RECV                    = 61; // u8
export const NODE_COL_EV_FIRE                    = 62; // u8
export const NODE_COL_EV_SEND                    = 63; // u8
export const NODE_COL_EV_ARRIVE                  = 64; // u8
export const NODE_COL_EV_DONE                    = 65; // u8
export const NODE_COL_SELECTED                   = 66; // u8
export const NODE_COL_KIND_ID                    = 67; // u8
export const NODE_COL_LABEL_OFF                  = 68; // u32
export const NODE_COL_LABEL_LEN                  = 72; // u32
export const NODE_COL_FADED                      = 76; // u8
export const NODE_COL_HOVERED                    = 77; // u8
export const NODE_STRIDE                         = 78;

export function readNodeCX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CX, true); }
export function readNodeCY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CY, true); }
export function readNodeCZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CZ, true); }
export function readNodeRadius(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RADIUS, true); }
export function readNodeSphereR(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_SPHERE_R, true); }
export function readNodeVRX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_VRX, true); }
export function readNodeVRY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_VRY, true); }
export function readNodeVRZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_VRZ, true); }
export function readNodeFRX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_FRX, true); }
export function readNodeFRY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_FRY, true); }
export function readNodeFRZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_FRZ, true); }
export function readNodeTorusRed(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_TORUS_RED); }
export function readNodeMissVal(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_MISS_VAL, true); }
export function readNodeMX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_MX, true); }
export function readNodeMY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_MY, true); }
export function readNodeMZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_MZ, true); }
export function readNodeEvRecv(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_EV_RECV); }
export function readNodeEvFire(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_EV_FIRE); }
export function readNodeEvSend(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_EV_SEND); }
export function readNodeEvArrive(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_EV_ARRIVE); }
export function readNodeEvDone(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_EV_DONE); }
export function readNodeSelected(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_SELECTED); }
export function readNodeKindId(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_KIND_ID); }
export function readNodeLabelOff(view: DataView, row: number): number { return view.getUint32(row * NODE_STRIDE + NODE_COL_LABEL_OFF, true); }
export function readNodeLabelLen(view: DataView, row: number): number { return view.getUint32(row * NODE_STRIDE + NODE_COL_LABEL_LEN, true); }
export function readNodeFaded(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_FADED); }
export function readNodeHovered(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_HOVERED); }

// ── Interior block ───────────────────────────────────────────
export const INTERIOR_COL_PRESENT                = 0; // u8
export const INTERIOR_COL_VALUE                  = 1; // i32
export const INTERIOR_COL_OX                     = 5; // f32
export const INTERIOR_COL_OY                     = 9; // f32
export const INTERIOR_COL_OZ                     = 13; // f32
export const INTERIOR_STRIDE                     = 17;

export function readInteriorPresent(view: DataView, row: number): number { return view.getUint8(row * INTERIOR_STRIDE + INTERIOR_COL_PRESENT); }
export function readInteriorValue(view: DataView, row: number): number { return view.getInt32(row * INTERIOR_STRIDE + INTERIOR_COL_VALUE, true); }
export function readInteriorOX(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_OX, true); }
export function readInteriorOY(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_OY, true); }
export function readInteriorOZ(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_OZ, true); }

// ── Edge block ───────────────────────────────────────────────
export const EDGE_COL_SX                         = 0; // f32
export const EDGE_COL_SY                         = 4; // f32
export const EDGE_COL_SZ                         = 8; // f32
export const EDGE_COL_EX                         = 12; // f32
export const EDGE_COL_EY                         = 16; // f32
export const EDGE_COL_EZ                         = 20; // f32
export const EDGE_COL_SRC_NODE_ROW               = 24; // i32
export const EDGE_COL_DST_NODE_ROW               = 28; // i32
export const EDGE_COL_SELECTED                   = 32; // u8
export const EDGE_COL_FADED                      = 33; // u8
export const EDGE_COL_EDGE_LABEL_OFF             = 34; // u32
export const EDGE_COL_EDGE_LABEL_LEN             = 38; // u32
export const EDGE_STRIDE                         = 42;

export function readEdgeSX(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_SX, true); }
export function readEdgeSY(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_SY, true); }
export function readEdgeSZ(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_SZ, true); }
export function readEdgeEX(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_EX, true); }
export function readEdgeEY(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_EY, true); }
export function readEdgeEZ(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_EZ, true); }
export function readEdgeSrcNodeRow(view: DataView, row: number): number { return view.getInt32(row * EDGE_STRIDE + EDGE_COL_SRC_NODE_ROW, true); }
export function readEdgeDstNodeRow(view: DataView, row: number): number { return view.getInt32(row * EDGE_STRIDE + EDGE_COL_DST_NODE_ROW, true); }
export function readEdgeSelected(view: DataView, row: number): number { return view.getUint8(row * EDGE_STRIDE + EDGE_COL_SELECTED); }
export function readEdgeFaded(view: DataView, row: number): number { return view.getUint8(row * EDGE_STRIDE + EDGE_COL_FADED); }
export function readEdgeEdgeLabelOff(view: DataView, row: number): number { return view.getUint32(row * EDGE_STRIDE + EDGE_COL_EDGE_LABEL_OFF, true); }
export function readEdgeEdgeLabelLen(view: DataView, row: number): number { return view.getUint32(row * EDGE_STRIDE + EDGE_COL_EDGE_LABEL_LEN, true); }

// ── Port block ───────────────────────────────────────────────
export const PORT_COL_NODE_ROW                   = 0; // i32
export const PORT_COL_DX                         = 4; // f32
export const PORT_COL_DY                         = 8; // f32
export const PORT_COL_DZ                         = 12; // f32
export const PORT_COL_IS_INPUT                   = 16; // u8
export const PORT_COL_HOVERED                    = 17; // u8
export const PORT_COL_PORT_NAME_OFF              = 18; // u32
export const PORT_COL_PORT_NAME_LEN              = 22; // u32
export const PORT_STRIDE                         = 26;

export function readPortNodeRow(view: DataView, row: number): number { return view.getInt32(row * PORT_STRIDE + PORT_COL_NODE_ROW, true); }
export function readPortDX(view: DataView, row: number): number { return view.getFloat32(row * PORT_STRIDE + PORT_COL_DX, true); }
export function readPortDY(view: DataView, row: number): number { return view.getFloat32(row * PORT_STRIDE + PORT_COL_DY, true); }
export function readPortDZ(view: DataView, row: number): number { return view.getFloat32(row * PORT_STRIDE + PORT_COL_DZ, true); }
export function readPortIsInput(view: DataView, row: number): number { return view.getUint8(row * PORT_STRIDE + PORT_COL_IS_INPUT); }
export function readPortHovered(view: DataView, row: number): number { return view.getUint8(row * PORT_STRIDE + PORT_COL_HOVERED); }
export function readPortPortNameOff(view: DataView, row: number): number { return view.getUint32(row * PORT_STRIDE + PORT_COL_PORT_NAME_OFF, true); }
export function readPortPortNameLen(view: DataView, row: number): number { return view.getUint32(row * PORT_STRIDE + PORT_COL_PORT_NAME_LEN, true); }

// ── Camera block ─────────────────────────────────────────────
export const CAMERA_COL_PX                       = 0; // f32
export const CAMERA_COL_PY                       = 4; // f32
export const CAMERA_COL_PZ                       = 8; // f32
export const CAMERA_COL_R                        = 12; // f32
export const CAMERA_COL_POS_THETA                = 16; // f32
export const CAMERA_COL_POS_PHI                  = 20; // f32
export const CAMERA_COL_UP_THETA                 = 24; // f32
export const CAMERA_COL_UP_PHI                   = 28; // f32
export const CAMERA_STRIDE                       = 32;

export function readCameraPX(view: DataView): number { return view.getFloat32(CAMERA_COL_PX, true); }
export function readCameraPY(view: DataView): number { return view.getFloat32(CAMERA_COL_PY, true); }
export function readCameraPZ(view: DataView): number { return view.getFloat32(CAMERA_COL_PZ, true); }
export function readCameraR(view: DataView): number { return view.getFloat32(CAMERA_COL_R, true); }
export function readCameraPosTheta(view: DataView): number { return view.getFloat32(CAMERA_COL_POS_THETA, true); }
export function readCameraPosPhi(view: DataView): number { return view.getFloat32(CAMERA_COL_POS_PHI, true); }
export function readCameraUpTheta(view: DataView): number { return view.getFloat32(CAMERA_COL_UP_THETA, true); }
export function readCameraUpPhi(view: DataView): number { return view.getFloat32(CAMERA_COL_UP_PHI, true); }

// ── Overlay block ────────────────────────────────────────────
export const OVERLAY_COL_SCENE_TORI              = 0; // u8
export const OVERLAY_COL_SCENE_POLES             = 1; // u8
export const OVERLAY_COL_NODE_POLES              = 2; // u8
export const OVERLAY_COL_ANGLE_LABELS            = 3; // u8
export const OVERLAY_COL_SEL_SPHERE_POLES        = 4; // u8
export const OVERLAY_COL_HANDHOLDS               = 5; // u8
export const OVERLAY_COL_LABELS_GLOBAL           = 6; // u8
export const OVERLAY_COL_BADGES_GLOBAL           = 7; // u8
export const OVERLAY_COL_OVERLAYS_VIS            = 8; // u8
export const OVERLAY_COL_DOUBLE_LINKS            = 9; // u8
export const OVERLAY_COL_SEL_MODE                = 10; // u8
export const OVERLAY_STRIDE                      = 11;

export function readOverlaySceneTori(view: DataView): number { return view.getUint8(OVERLAY_COL_SCENE_TORI); }
export function readOverlayScenePoles(view: DataView): number { return view.getUint8(OVERLAY_COL_SCENE_POLES); }
export function readOverlayNodePoles(view: DataView): number { return view.getUint8(OVERLAY_COL_NODE_POLES); }
export function readOverlayAngleLabels(view: DataView): number { return view.getUint8(OVERLAY_COL_ANGLE_LABELS); }
export function readOverlaySelSpherePoles(view: DataView): number { return view.getUint8(OVERLAY_COL_SEL_SPHERE_POLES); }
export function readOverlayHandholds(view: DataView): number { return view.getUint8(OVERLAY_COL_HANDHOLDS); }
export function readOverlayLabelsGlobal(view: DataView): number { return view.getUint8(OVERLAY_COL_LABELS_GLOBAL); }
export function readOverlayBadgesGlobal(view: DataView): number { return view.getUint8(OVERLAY_COL_BADGES_GLOBAL); }
export function readOverlayOverlaysVis(view: DataView): number { return view.getUint8(OVERLAY_COL_OVERLAYS_VIS); }
export function readOverlayDoubleLinks(view: DataView): number { return view.getUint8(OVERLAY_COL_DOUBLE_LINKS); }
export function readOverlaySelMode(view: DataView): number { return view.getUint8(OVERLAY_COL_SEL_MODE); }

// ── Event block ──────────────────────────────────────────────
export const EVENT_COL_KIND                      = 0; // u8
export const EVENT_COL_NODE_ROW                  = 1; // i32
export const EVENT_COL_PORT_ROW                  = 5; // i32
export const EVENT_COL_TARGET_ROW                = 9; // i32
export const EVENT_COL_TARGET_PORT_ROW           = 13; // i32
export const EVENT_COL_EDGE_ROW                  = 17; // i32
export const EVENT_COL_SLOT                      = 21; // i32
export const EVENT_COL_VALUE                     = 25; // i32
export const EVENT_COL_BEAD                      = 29; // u32
export const EVENT_COL_ARC_LENGTH                = 33; // f32
export const EVENT_COL_SIM_LATENCY_MS            = 37; // f32
export const EVENT_COL_X                         = 41; // f32
export const EVENT_COL_Y                         = 45; // f32
export const EVENT_COL_Z                         = 49; // f32
export const EVENT_COL_F                         = 53; // f32
export const EVENT_STRIDE                        = 57;

export function readEventKind(view: DataView, row: number): number { return view.getUint8(row * EVENT_STRIDE + EVENT_COL_KIND); }
export function readEventNodeRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_NODE_ROW, true); }
export function readEventPortRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_PORT_ROW, true); }
export function readEventTargetRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_TARGET_ROW, true); }
export function readEventTargetPortRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_TARGET_PORT_ROW, true); }
export function readEventEdgeRow(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_EDGE_ROW, true); }
export function readEventSlot(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_SLOT, true); }
export function readEventValue(view: DataView, row: number): number { return view.getInt32(row * EVENT_STRIDE + EVENT_COL_VALUE, true); }
export function readEventBead(view: DataView, row: number): number { return view.getUint32(row * EVENT_STRIDE + EVENT_COL_BEAD, true); }
export function readEventArcLength(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_ARC_LENGTH, true); }
export function readEventSimLatencyMs(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_SIM_LATENCY_MS, true); }
export function readEventX(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_X, true); }
export function readEventY(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_Y, true); }
export function readEventZ(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_Z, true); }
export function readEventF(view: DataView, row: number): number { return view.getFloat32(row * EVENT_STRIDE + EVENT_COL_F, true); }

// ── Semantic event enum ─────────────────────────────────────────────────────────
// Transient per-node event flags; ids embedded in snapshots, names in this schema.
export const BUF_EVENT_RECV            = 0;
export const BUF_EVENT_FIRE            = 1;
export const BUF_EVENT_SEND            = 2;
export const BUF_EVENT_ARRIVE          = 3;
export const BUF_EVENT_DONE            = 4;
