// GENERATED by tools/gen-node-defs — do not edit.
// Source: Buffer/layout.go  Regenerate: npm run gen:node-defs
// BUF_LAYOUT_FINGERPRINT: version:4|block:Bead[X:f32:0,Y:f32:4,Z:f32:8,Value:i32:12,Frac:f32:16,BeadID:u32:20,Live:u8:24]:stride:25|block:Node[CX:f32:0,CY:f32:4,CZ:f32:8,Radius:f32:12,SphereR:f32:16,TorusRed:u8:20,MissVal:i32:21,MX:f32:25,MY:f32:29,MZ:f32:33,EvRecv:u8:37,EvFire:u8:38,EvSend:u8:39,EvArrive:u8:40,EvDone:u8:41,Selected:u8:42]:stride:43|block:Interior[Present:u8:0,Value:i32:1,OX:f32:5,OY:f32:9,OZ:f32:13]:stride:17|block:Edge[SX:f32:0,SY:f32:4,SZ:f32:8,EX:f32:12,EY:f32:16,EZ:f32:20,SrcNodeRow:i32:24,DstNodeRow:i32:28]:stride:32|block:Camera[PX:f32:0,PY:f32:4,PZ:f32:8,R:f32:12,PosTheta:f32:16,PosPhi:f32:20,UpTheta:f32:24,UpPhi:f32:28]:stride:32|block:Overlay[SceneTori:u8:0,ScenePoles:u8:1,NodePoles:u8:2,AngleLabels:u8:3,SelSpherePoles:u8:4,Handholds:u8:5,LabelsGlobal:u8:6,BadgesGlobal:u8:7,OverlaysVis:u8:8,DoubleLinks:u8:9]:stride:10|event[Recv:0,Fire:1,Send:2,Arrive:3,Done:4]

/** Schema version — must match BufLayoutVersion in Buffer/layout.go. */
export const BUF_LAYOUT_VERSION = 4;

/** Snapshot header: [tick:u32][beadCount:u32][nodeCount:u32][edgeCount:u32] */
export const BUF_HEADER_SIZE = 16;

// ── Bead block ───────────────────────────────────────────────
export const BEAD_COL_X                          = 0; // f32
export const BEAD_COL_Y                          = 4; // f32
export const BEAD_COL_Z                          = 8; // f32
export const BEAD_COL_VALUE                      = 12; // i32
export const BEAD_COL_FRAC                       = 16; // f32
export const BEAD_COL_BEAD_ID                    = 20; // u32
export const BEAD_COL_LIVE                       = 24; // u8
export const BEAD_STRIDE                         = 25;

export function readBeadX(view: DataView, row: number): number { return view.getFloat32(row * BEAD_STRIDE + BEAD_COL_X, true); }
export function readBeadY(view: DataView, row: number): number { return view.getFloat32(row * BEAD_STRIDE + BEAD_COL_Y, true); }
export function readBeadZ(view: DataView, row: number): number { return view.getFloat32(row * BEAD_STRIDE + BEAD_COL_Z, true); }
export function readBeadValue(view: DataView, row: number): number { return view.getInt32(row * BEAD_STRIDE + BEAD_COL_VALUE, true); }
export function readBeadFrac(view: DataView, row: number): number { return view.getFloat32(row * BEAD_STRIDE + BEAD_COL_FRAC, true); }
export function readBeadBeadID(view: DataView, row: number): number { return view.getUint32(row * BEAD_STRIDE + BEAD_COL_BEAD_ID, true); }
export function readBeadLive(view: DataView, row: number): number { return view.getUint8(row * BEAD_STRIDE + BEAD_COL_LIVE); }

// ── Node block ───────────────────────────────────────────────
export const NODE_COL_CX                         = 0; // f32
export const NODE_COL_CY                         = 4; // f32
export const NODE_COL_CZ                         = 8; // f32
export const NODE_COL_RADIUS                     = 12; // f32
export const NODE_COL_SPHERE_R                   = 16; // f32
export const NODE_COL_TORUS_RED                  = 20; // u8
export const NODE_COL_MISS_VAL                   = 21; // i32
export const NODE_COL_MX                         = 25; // f32
export const NODE_COL_MY                         = 29; // f32
export const NODE_COL_MZ                         = 33; // f32
export const NODE_COL_EV_RECV                    = 37; // u8
export const NODE_COL_EV_FIRE                    = 38; // u8
export const NODE_COL_EV_SEND                    = 39; // u8
export const NODE_COL_EV_ARRIVE                  = 40; // u8
export const NODE_COL_EV_DONE                    = 41; // u8
export const NODE_COL_SELECTED                   = 42; // u8
export const NODE_STRIDE                         = 43;

export function readNodeCX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CX, true); }
export function readNodeCY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CY, true); }
export function readNodeCZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_CZ, true); }
export function readNodeRadius(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_RADIUS, true); }
export function readNodeSphereR(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_SPHERE_R, true); }
export function readNodeTorusRed(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_TORUS_RED); }
export function readNodeMissVal(view: DataView, row: number): number { return view.getInt32(row * NODE_STRIDE + NODE_COL_MISS_VAL, true); }
export function readNodeMX(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_MX, true); }
export function readNodeMY(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_MY, true); }
export function readNodeMZ(view: DataView, row: number): number { return view.getFloat32(row * NODE_STRIDE + NODE_COL_MZ, true); }
export function readNodeEvRecv(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_EV_RECV); }
export function readNodeEvFire(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_EV_FIRE); }
export function readNodeEvSend(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_EV_SEND); }
export function readNodeEvArrive(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_EV_ARRIVE); }
export function readNodeEvDone(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_EV_DONE); }
export function readNodeSelected(view: DataView, row: number): number { return view.getUint8(row * NODE_STRIDE + NODE_COL_SELECTED); }

// ── Interior block ───────────────────────────────────────────
export const INTERIOR_COL_PRESENT                = 0; // u8
export const INTERIOR_COL_VALUE                  = 1; // i32
export const INTERIOR_COL_OX                     = 5; // f32
export const INTERIOR_COL_OY                     = 9; // f32
export const INTERIOR_COL_OZ                     = 13; // f32
export const INTERIOR_STRIDE                     = 17;

export function readInteriorPresent(view: DataView, row: number): number { return view.getUint8(row * INTERIOR_STRIDE + INTERIOR_COL_PRESENT); }
export function readInteriorValue(view: DataView, row: number): number { return view.getInt32(row * INTERIOR_STRIDE + INTERIOR_COL_VALUE, true); }
export function readInteriorOX(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_OX, true); }
export function readInteriorOY(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_OY, true); }
export function readInteriorOZ(view: DataView, row: number): number { return view.getFloat32(row * INTERIOR_STRIDE + INTERIOR_COL_OZ, true); }

// ── Edge block ───────────────────────────────────────────────
export const EDGE_COL_SX                         = 0; // f32
export const EDGE_COL_SY                         = 4; // f32
export const EDGE_COL_SZ                         = 8; // f32
export const EDGE_COL_EX                         = 12; // f32
export const EDGE_COL_EY                         = 16; // f32
export const EDGE_COL_EZ                         = 20; // f32
export const EDGE_COL_SRC_NODE_ROW               = 24; // i32
export const EDGE_COL_DST_NODE_ROW               = 28; // i32
export const EDGE_STRIDE                         = 32;

export function readEdgeSX(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_SX, true); }
export function readEdgeSY(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_SY, true); }
export function readEdgeSZ(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_SZ, true); }
export function readEdgeEX(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_EX, true); }
export function readEdgeEY(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_EY, true); }
export function readEdgeEZ(view: DataView, row: number): number { return view.getFloat32(row * EDGE_STRIDE + EDGE_COL_EZ, true); }
export function readEdgeSrcNodeRow(view: DataView, row: number): number { return view.getInt32(row * EDGE_STRIDE + EDGE_COL_SRC_NODE_ROW, true); }
export function readEdgeDstNodeRow(view: DataView, row: number): number { return view.getInt32(row * EDGE_STRIDE + EDGE_COL_DST_NODE_ROW, true); }

// ── Camera block ─────────────────────────────────────────────
export const CAMERA_COL_PX                       = 0; // f32
export const CAMERA_COL_PY                       = 4; // f32
export const CAMERA_COL_PZ                       = 8; // f32
export const CAMERA_COL_R                        = 12; // f32
export const CAMERA_COL_POS_THETA                = 16; // f32
export const CAMERA_COL_POS_PHI                  = 20; // f32
export const CAMERA_COL_UP_THETA                 = 24; // f32
export const CAMERA_COL_UP_PHI                   = 28; // f32
export const CAMERA_STRIDE                       = 32;

export function readCameraPX(view: DataView): number { return view.getFloat32(CAMERA_COL_PX, true); }
export function readCameraPY(view: DataView): number { return view.getFloat32(CAMERA_COL_PY, true); }
export function readCameraPZ(view: DataView): number { return view.getFloat32(CAMERA_COL_PZ, true); }
export function readCameraR(view: DataView): number { return view.getFloat32(CAMERA_COL_R, true); }
export function readCameraPosTheta(view: DataView): number { return view.getFloat32(CAMERA_COL_POS_THETA, true); }
export function readCameraPosPhi(view: DataView): number { return view.getFloat32(CAMERA_COL_POS_PHI, true); }
export function readCameraUpTheta(view: DataView): number { return view.getFloat32(CAMERA_COL_UP_THETA, true); }
export function readCameraUpPhi(view: DataView): number { return view.getFloat32(CAMERA_COL_UP_PHI, true); }

// ── Overlay block ────────────────────────────────────────────
export const OVERLAY_COL_SCENE_TORI              = 0; // u8
export const OVERLAY_COL_SCENE_POLES             = 1; // u8
export const OVERLAY_COL_NODE_POLES              = 2; // u8
export const OVERLAY_COL_ANGLE_LABELS            = 3; // u8
export const OVERLAY_COL_SEL_SPHERE_POLES        = 4; // u8
export const OVERLAY_COL_HANDHOLDS               = 5; // u8
export const OVERLAY_COL_LABELS_GLOBAL           = 6; // u8
export const OVERLAY_COL_BADGES_GLOBAL           = 7; // u8
export const OVERLAY_COL_OVERLAYS_VIS            = 8; // u8
export const OVERLAY_COL_DOUBLE_LINKS            = 9; // u8
export const OVERLAY_STRIDE                      = 10;

export function readOverlaySceneTori(view: DataView): number { return view.getUint8(OVERLAY_COL_SCENE_TORI); }
export function readOverlayScenePoles(view: DataView): number { return view.getUint8(OVERLAY_COL_SCENE_POLES); }
export function readOverlayNodePoles(view: DataView): number { return view.getUint8(OVERLAY_COL_NODE_POLES); }
export function readOverlayAngleLabels(view: DataView): number { return view.getUint8(OVERLAY_COL_ANGLE_LABELS); }
export function readOverlaySelSpherePoles(view: DataView): number { return view.getUint8(OVERLAY_COL_SEL_SPHERE_POLES); }
export function readOverlayHandholds(view: DataView): number { return view.getUint8(OVERLAY_COL_HANDHOLDS); }
export function readOverlayLabelsGlobal(view: DataView): number { return view.getUint8(OVERLAY_COL_LABELS_GLOBAL); }
export function readOverlayBadgesGlobal(view: DataView): number { return view.getUint8(OVERLAY_COL_BADGES_GLOBAL); }
export function readOverlayOverlaysVis(view: DataView): number { return view.getUint8(OVERLAY_COL_OVERLAYS_VIS); }
export function readOverlayDoubleLinks(view: DataView): number { return view.getUint8(OVERLAY_COL_DOUBLE_LINKS); }

// ── Semantic event enum ─────────────────────────────────────────────────────────
// Transient per-node event flags; ids embedded in snapshots, names in this schema.
export const BUF_EVENT_RECV            = 0;
export const BUF_EVENT_FIRE            = 1;
export const BUF_EVENT_SEND            = 2;
export const BUF_EVENT_ARRIVE          = 3;
export const BUF_EVENT_DONE            = 4;
