// GENERATED by tools/gen-node-defs — do not edit.
// Source: nodes/Wiring/curve_params.go CurveParam* constants.
// Regenerate with: npm run gen:node-defs

export const CURVE_PARAM_PULSE_SPEED_WU_PER_MS = 0.08;
export const CURVE_PARAM_MIN_ARC_LENGTH = 1.0;
export const CURVE_PARAM_BULGE_FACTOR = 0.25;
export const CURVE_PARAM_BEZIER_SAMPLE_COUNT = 64;
export const CURVE_PARAM_NODE_RADIUS_DIVISOR = 4;
export const CURVE_PARAM_SLOT_PCT0 = 25;
export const CURVE_PARAM_SLOT_PCT1 = 50;
export const CURVE_PARAM_SLOT_PCT2 = 75;
