// GENERATED by tools/gen-node-defs — do not edit. Source: nodes/<Kind>/<Kind>.go wire:"data.*" tags.
// Validates node.data blobs against Go struct field types.

import { ParseError } from "./parse-primitives";

export interface HoldData {
  state: {
    held: number;
  };
}

export interface HoldNewSendOldData {
  state: {
    held: number;
  };
}

export interface InputData {
  init: number[];
  repeat: boolean;
}

export interface PacerData {
  state: {
    held: number;
  };
}

// parseNodeData validates node.data for known kinds. Unknown kinds pass through.
// Throws ParseError if the data shape does not match the Go struct.
export function parseNodeData(kind: string, data: unknown, path: string): unknown {
  if (data === undefined || data === null) return data;
  switch (kind) {
    case "Hold": {
      if (typeof data !== "object" || Array.isArray(data)) throw new ParseError(path+".data: expected object");
      const d = data as Record<string, unknown>;
    { const p = d["state"] as Record<string, unknown>|undefined; if (!p || typeof p !== "object") throw new ParseError(path+".data.state: expected object"); if (typeof p["held"] !== "number") throw new ParseError(path+".data.state.held: expected number"); }
      return data;
    }
    case "HoldFlip":
      return data; // no wire:"data.*" fields on the Go struct
    case "HoldNewSendOld": {
      if (typeof data !== "object" || Array.isArray(data)) throw new ParseError(path+".data: expected object");
      const d = data as Record<string, unknown>;
    { const p = d["state"] as Record<string, unknown>|undefined; if (!p || typeof p !== "object") throw new ParseError(path+".data.state: expected object"); if (typeof p["held"] !== "number") throw new ParseError(path+".data.state.held: expected number"); }
      return data;
    }
    case "Input": {
      if (typeof data !== "object" || Array.isArray(data)) throw new ParseError(path+".data: expected object");
      const d = data as Record<string, unknown>;
    if (!Array.isArray(d["init"]) || !(d["init"] as unknown[]).every((x) => typeof x === "number")) throw new ParseError(path+".data.init: expected number[]");
    if (typeof d["repeat"] !== "boolean") throw new ParseError(path+".data.repeat: expected boolean");
      return data;
    }
    case "Pacer": {
      if (typeof data !== "object" || Array.isArray(data)) throw new ParseError(path+".data: expected object");
      const d = data as Record<string, unknown>;
    { const p = d["state"] as Record<string, unknown>|undefined; if (!p || typeof p !== "object") throw new ParseError(path+".data.state: expected object"); if (typeof p["held"] !== "number") throw new ParseError(path+".data.state.held: expected number"); }
      return data;
    }
    case "Pulse":
      return data; // no wire:"data.*" fields on the Go struct
    case "WindowAndInhibitLeftGate":
      return data; // no wire:"data.*" fields on the Go struct
    case "WindowAndInhibitRightGate":
      return data; // no wire:"data.*" fields on the Go struct
    default:
      return data;
  }
}
