// GENERATED by tools/gen-node-defs — do not edit.
// Source: nodes/Wiring/shading_params.go ShadingParam* constants.
// Regenerate with: npm run gen:node-defs
//
// Go owns the shading PARAMETER values (MODEL.md). TS reads these and applies
// them to GPU materials / bakes the env map from them — no shading values of its
// own. The GPU machinery (three.js materials, PMREM bake, binding) stays in TS.

export const SHADING_PARAM_NODE_TRANSMISSION = 1.0;
export const SHADING_PARAM_NODE_THICKNESS = 0.0;
export const SHADING_PARAM_NODE_ROUGHNESS = 0.12;
export const SHADING_PARAM_NODE_IOR = 1.5;
export const SHADING_PARAM_NODE_METALNESS = 0.0;
export const SHADING_PARAM_NODE_CLEARCOAT = 0.0;
export const SHADING_PARAM_NODE_CLEARCOAT_ROUGHNESS = 0.1;
export const SHADING_PARAM_NODE_ENV_MAP_INTENSITY = 1.0;
export const SHADING_PARAM_NODE_OPACITY = 0.92;
export const SHADING_PARAM_NODE_FADE_OPACITY = 0.25;
export const SHADING_PARAM_NODE_FADE_BODY_MUL = 0.6;
export const SHADING_PARAM_ENV_SKY_TOP_R = 0.78;
export const SHADING_PARAM_ENV_SKY_TOP_G = 0.77;
export const SHADING_PARAM_ENV_SKY_TOP_B = 0.74;
export const SHADING_PARAM_ENV_SKY_BOTTOM_R = 1.0;
export const SHADING_PARAM_ENV_SKY_BOTTOM_G = 0.88;
export const SHADING_PARAM_ENV_SKY_BOTTOM_B = 0.75;
export const SHADING_PARAM_ENV_SKY_RADIUS = 50.0;
export const SHADING_PARAM_ENV_AMBIENT_COLOR = "#ffffff";
export const SHADING_PARAM_ENV_AMBIENT_INTENSITY = 0.9;
export const SHADING_PARAM_ENV_KEY_COLOR = "#ffeedd";
export const SHADING_PARAM_ENV_KEY_INTENSITY = 0.45;
export const SHADING_PARAM_ENV_RIM_COLOR = "#aabbff";
export const SHADING_PARAM_ENV_RIM_INTENSITY = 0.3;
export const SHADING_PARAM_ENV_PMREM_BLUR = 0.04;
export const SHADING_PARAM_SCENE_AMBIENT_INTENSITY = 0.6;
export const SHADING_PARAM_SCENE_DIR_INTENSITY = 0.8;
export const SHADING_PARAM_TUBE_COLOR = "#5599cc";
export const SHADING_PARAM_TUBE_EMISSIVE = "#2255aa";
export const SHADING_PARAM_TUBE_EMISSIVE_INTENSITY = 0.8;
export const SHADING_PARAM_BEAD_COLOR = "#ffffff";
export const SHADING_PARAM_BEAD_EMISSIVE = "#ffffff";
export const SHADING_PARAM_BEAD_EMISSIVE_INTENSITY = 2.5;
export const SHADING_PARAM_LAYOUT_LINK_COLOR = "#00e5ff";
export const SHADING_PARAM_LAYOUT_LINK_EMISSIVE = "#00e5ff";
export const SHADING_PARAM_LAYOUT_LINK_EMISSIVE_INTENSITY = 0.8;
