// GENERATED by tools/gen-node-defs — do not edit.
// Source: Trace/Trace.go Kind* constants + BreadcrumbLabels. Regenerate with: npm run gen:node-defs

export const TRACE_EVENT_KINDS = ["recv", "fire", "send", "edge-bead", "geometry", "node-geometry", "arrive", "node-bead", "camera", "scene-tori", "scene-poles", "node-poles", "sel-sphere-poles", "handholds", "labels-global", "overlays-vis", "double-links", "layout-link", "select", "hover", "scene-sphere", "abc-drag", "abc-drag-reset", "breadcrumb"] as const;

export type TraceEventKind = (typeof TRACE_EVENT_KINDS)[number];

// BREADCRUMB_LABELS is indexed by the buffer EVENT block's Label column
// (Kind==KindBreadcrumb rows only) — see Trace.go's BreadcrumbLabel* consts.
export const BREADCRUMB_LABELS = ["topology-loaded", "row-seed-count-mismatch", "pole-toggle-go", "window_clear", "window_open", "dwell_start", "abc-drag", "wire-send-buffer-full", "cascade.root"] as const;
