// GENERATED by tools/gen-node-defs — do not edit.
// Source: Trace/Trace.go Kind* constants. Regenerate with: npm run gen:node-defs

export const TRACE_EVENT_KINDS = ["recv", "fire", "send", "done", "edge-bead", "geometry", "pulse-cancelled", "node-geometry", "arrive", "node-bead", "camera", "scene-tori", "scene-poles", "node-poles", "sel-sphere-poles", "handholds", "labels-global", "overlays-vis", "double-links", "layout-link", "select", "fade", "hover", "scene-sphere", "halted"] as const;

export type TraceEventKind = (typeof TRACE_EVENT_KINDS)[number];
