// GENERATED by tools/gen-node-defs — do not edit.
// Source: Trace/Trace.go MarshalJSON node-status payload struct.
// Regenerate with: npm run gen:node-defs

export interface NodeStatusEvent {
  step: number;
  kind: "node-status";
  node: string;
  torusRed: boolean;
  missedValue: number;
  x: number;
  y: number;
  z: number;
}

/** Field-level validator for the node-status trace payload, generated from
 *  Trace.go field-for-field. `step` is validated by the caller (numeric
 *  envelope) and `kind` by the TRACE_EVENT_KINDS set, so only the payload
 *  fields are checked here. Malformed Go payloads are dropped, not cast. */
export function validateNodeStatusFields(obj: Record<string, unknown>): boolean {
  return (
    typeof obj["node"] === "string" &&
    typeof obj["torusRed"] === "boolean" &&
    typeof obj["missedValue"] === "number" &&
    typeof obj["x"] === "number" &&
    typeof obj["y"] === "number" &&
    typeof obj["z"] === "number"
  );
}
