// GENERATED by tools/gen-node-defs — do not edit. Source: nodes/Wiring/loader.go wire:"prop,..." tags.

export interface WirePropDef {
  tsType: string;
  required: boolean;
}

export const WIRE_PROPS: Record<string, WirePropDef> = {
  label:       { tsType: "string",    required: false },
  valueLabel:  { tsType: "string",    required: false },
  lane:        { tsType: "number",    required: false },
  arrowStyle:  { tsType: "ArrowStyle", required: false },
  concurrent:  { tsType: "boolean",   required: false },
  kind:        { tsType: "EdgeKind",  required: true },
};

export type WirePropName = keyof typeof WIRE_PROPS;
