// GENERATED by: go run ./tools/gen-node-defs (regenerate after editing wire:"..." tags in nodes/Wiring/loader.go)
// Source: nodes/Wiring/loader.go wire:"prop,..." tags. Do not edit by hand.

import type { ArrowStyle, EdgeKind } from "./types";

export interface WirePropDef {
  tsType: string;
  required: boolean;
}

export const WIRE_PROPS: Record<string, WirePropDef> = {
  label:       { tsType: "string",    required: false },
  arrowStyle:  { tsType: "ArrowStyle", required: false },
  concurrent:  { tsType: "boolean",   required: false },
  kind:        { tsType: "EdgeKind",  required: true },
};

export type WirePropName = keyof typeof WIRE_PROPS;

// Derived from WIRE_PROPS — do not hand-edit. Consumed by Edge and EdgeData.
export type WireProps = {
  label?: string;
  arrowStyle?: ArrowStyle;
  concurrent?: boolean;
  kind: EdgeKind;
};
