// node_dims_gen.go / node_kind_id_gen.go emitters: per-kind render dimensions
// (mirrors SPEC.md View width/height) and the buffer KindId numbering.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
)

// writeNodeDims emits nodes/Wiring/node_dims_gen.go: a kind → render width/height
// map sourced from each kind's SPEC.md ## View width/height fields. The Go
// Go uses these to mirror nodeRadius/nodeWorldPos in geometry-helpers.ts
// when computing port-to-port arc length. Single source of truth = SPEC.md.
func writeNodeDims(outPath string, kinds []kindEntry) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: nodes/<Kind>/SPEC.md ## View width/height fields.`)
	fmt.Fprintln(w, `// Regenerate with: cd tools/topology-vscode && npm run gen:node-defs`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `package Wiring`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// kindDim is the render width/height for one node kind, mirroring`)
	fmt.Fprintln(w, `// NODE_DEFS[kind].width/height in node-defs.ts.`)
	fmt.Fprintln(w, `type kindDim struct{ Width, Height float64 }`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// kindDims maps each runtime kind to its render dimensions.`)
	fmt.Fprintln(w, `var kindDims = map[string]kindDim{`)
	for _, e := range kinds {
		width := e.view.width
		height := e.view.height
		if width == "" {
			width = "110"
		}
		if height == "" {
			height = "60"
		}
		fmt.Fprintf(w, "\t%q: {Width: %s, Height: %s},\n", e.goKind, width, height)
	}
	fmt.Fprintln(w, `}`)

	w.Flush()
	// gofmt the generated Go so the output is canonical and the repo-wide
	// gofmt guard (tools/check-gofmt.sh) stays in agreement with check-generated.
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format node_dims_gen.go: %w", err)
	}
	return os.WriteFile(outPath, formatted, 0644)
}

// writeNodeKindID emits Buffer/node_kind_id_gen.go: a kind → uint8 index map so
// Go's SnapshotState can populate the KindId column in the buffer node block.
// The index is 0-based and follows the same alphabetical Go-kind sort order as
// NODE_DEFS_ARRAY in node-defs.ts, guaranteeing Go and TS use the same numbering.
func writeNodeKindID(outPath string, kinds []kindEntry) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: nodes/<Kind>/SPEC.md + Wiring.Register calls.`)
	fmt.Fprintln(w, `// Regenerate with: cd tools/topology-vscode && npm run gen:node-defs`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `package Buffer`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// KindIDUnknown is the sentinel KindId value when a node's kind is not in kindIDMap.`)
	fmt.Fprintln(w, `const KindIDUnknown uint8 = 0xFF`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// kindIDMap maps a node's Go kind name (PascalCase) to its 0-based index`)
	fmt.Fprintln(w, `// in the alphabetically-sorted NODE_DEFS_ARRAY emitted by the same generator.`)
	fmt.Fprintln(w, `// Index i here ↔ NODE_DEFS_ARRAY[i] on the TS side.`)
	fmt.Fprintln(w, `var kindIDMap = map[string]uint8{`)
	for i, e := range kinds {
		fmt.Fprintf(w, "\t%q: %d,\n", e.goKind, i)
	}
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// NodeKindID returns the buffer KindId for a node's Go kind string.`)
	fmt.Fprintln(w, `// Returns KindIDUnknown (0xFF) when the kind is not in the registry.`)
	fmt.Fprintln(w, `func NodeKindID(kind string) uint8 {`)
	fmt.Fprintln(w, `	if id, ok := kindIDMap[kind]; ok {`)
	fmt.Fprintln(w, `		return id`)
	fmt.Fprintln(w, `	}`)
	fmt.Fprintln(w, `	return KindIDUnknown`)
	fmt.Fprintln(w, `}`)

	w.Flush()
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format node_kind_id_gen.go: %w", err)
	}
	return os.WriteFile(outPath, formatted, 0644)
}
