// node-defs.ts emitter: builds NODE_DEFS/NODE_DEFS_ARRAY/NODE_KIND_NAMES from
// the parsed kindEntry slice.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"strings"
)

// writeNodeDefs emits the node-defs.ts file.
func writeNodeDefs(outPath string, kinds []kindEntry) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit. Source: nodes/<Kind>/<Kind>.go + SPEC.md`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `export interface NodeDef {`)
	fmt.Fprintln(w, `  bg: string;`)
	fmt.Fprintln(w, `  border: string;`)
	fmt.Fprintln(w, `  text: string;`)
	fmt.Fprintln(w, `  minWidth?: number;`)
	fmt.Fprintln(w, `  // NodeTypeDef-compatible fields for schema/adapter consumers.`)
	fmt.Fprintln(w, `  role?: string;`)
	fmt.Fprintln(w, `  shape?: string;`)
	fmt.Fprintln(w, `  fill?: string;`)
	fmt.Fprintln(w, `  stroke?: string;`)
	fmt.Fprintln(w, `  width?: number;`)
	fmt.Fprintln(w, `  height?: number;`)
	fmt.Fprintln(w, `  inputs?: { name: string; kind: string; isMulti?: boolean }[];`)
	fmt.Fprintln(w, `  outputs?: { name: string; kind: string; isMulti?: boolean }[];`)
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w)
	// Emit RUNTIME_IMPLEMENTED_KINDS from goKind names.
	fmt.Fprintln(w, `// PascalCase Go kind names that have a Go runtime.`)
	fmt.Fprintln(w, `// Single source of truth — derived from Wiring.Register calls.`)
	fmt.Fprintf(w, "export const RUNTIME_IMPLEMENTED_KINDS: ReadonlySet<string> = new Set([\n")
	for _, e := range kinds {
		fmt.Fprintf(w, "  %q,\n", e.goKind)
	}
	fmt.Fprintln(w, `]);`)
	fmt.Fprintln(w)
	// Pre-build the def strings so we can reuse them for both NODE_DEFS and NODE_DEFS_ARRAY.
	type kindDef struct {
		goKind string
		def    string
	}
	defs := make([]kindDef, len(kinds))
	for i, e := range kinds {
		defs[i] = kindDef{goKind: e.goKind, def: buildDef(e.view, e.ports)}
	}
	fmt.Fprintln(w, `export const NODE_DEFS: Record<string, NodeDef> = {`)
	for _, kd := range defs {
		fmt.Fprintf(w, "  %s: %s,\n", kd.goKind, kd.def)
	}
	fmt.Fprint(w, `};`, "\n")
	fmt.Fprintln(w)
	// NODE_DEFS_ARRAY: entries in the same alphabetical Go-kind order as NODE_DEFS,
	// matching the KindId index produced by Go's kindIDMap (Buffer/node_kind_id_gen.go).
	// Index i here ↔ KindId i in the buffer node block. Emitting literals directly
	// (not NODE_DEFS[key]) so tsc with noUncheckedIndexedAccess can't widen to NodeDef|undefined.
	fmt.Fprintf(w, "export const NODE_DEFS_ARRAY: readonly NodeDef[] = [\n")
	for _, kd := range defs {
		fmt.Fprintf(w, "  %s,\n", kd.def)
	}
	fmt.Fprintln(w, `];`)
	fmt.Fprintln(w)
	// NODE_KIND_NAMES: the PascalCase Go kind name for each KindId index, same alphabetical
	// order as NODE_DEFS_ARRAY (index i ↔ buffer KindId i). Used by the ext-host buffer-decoded
	// .probe logger to reconstruct a node-geometry event's `nodeKind` string from the numeric
	// KindId column, so no kind string is streamed per node.
	fmt.Fprintf(w, "export const NODE_KIND_NAMES: readonly string[] = [\n")
	for _, kd := range defs {
		fmt.Fprintf(w, "  %q,\n", kd.goKind)
	}
	fmt.Fprintln(w, `];`)

	w.Flush()
	return os.WriteFile(outPath, buf.Bytes(), 0644)
}

func buildDef(v viewDef, ports []port) string {
	targets := filterPorts(ports, "in")
	sources := filterPorts(ports, "out")

	var fields []string
	fields = append(fields, fmt.Sprintf(`bg: "%s"`, v.bg))
	fields = append(fields, fmt.Sprintf(`border: "%s"`, v.border))
	fields = append(fields, fmt.Sprintf(`text: "%s"`, v.text))
	if v.minWidth != "" {
		fields = append(fields, fmt.Sprintf(`minWidth: %s`, v.minWidth))
	}
	if v.role != "" {
		fields = append(fields, fmt.Sprintf(`role: "%s"`, v.role))
	}
	if v.shape != "" {
		fields = append(fields, fmt.Sprintf(`shape: "%s"`, v.shape))
	}
	if v.fill != "" {
		fields = append(fields, fmt.Sprintf(`fill: "%s"`, v.fill))
	}
	if v.stroke != "" {
		fields = append(fields, fmt.Sprintf(`stroke: "%s"`, v.stroke))
	}
	if v.width != "" {
		fields = append(fields, fmt.Sprintf(`width: %s`, v.width))
	}
	if v.height != "" {
		fields = append(fields, fmt.Sprintf(`height: %s`, v.height))
	}
	// Emit typed inputs/outputs for schema/adapter consumers.
	if len(targets) > 0 {
		fields = append(fields, fmt.Sprintf(`inputs: [%s]`, joinPortsTyped(targets)))
	}
	if len(sources) > 0 {
		fields = append(fields, fmt.Sprintf(`outputs: [%s]`, joinPortsTyped(sources)))
	}
	return "{ " + strings.Join(fields, ", ") + " }"
}

func filterPorts(ports []port, dir string) []port {
	var out []port
	for _, p := range ports {
		if p.direction == dir {
			out = append(out, p)
		}
	}
	return out
}

// joinPortsTyped emits {name, kind, isMulti?} pairs for NodeTypeDef-compatible consumers.
func joinPortsTyped(ports []port) string {
	var parts []string
	for _, p := range ports {
		ek := p.edgeKind
		if ek == "" {
			ek = "chain" // default
		}
		if p.isMulti {
			parts = append(parts, fmt.Sprintf(`{ name: "%s", kind: "%s", isMulti: true }`, p.id, ek))
		} else {
			parts = append(parts, fmt.Sprintf(`{ name: "%s", kind: "%s" }`, p.id, ek))
		}
	}
	return strings.Join(parts, ", ")
}
