// trace-kinds.ts emitter: scans Trace/ for Kind* string constants and emits
// TRACE_EVENT_KINDS.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

// parseTraceKinds scans EVERY non-test *.go file under the Trace/ dir and returns
// the string values of all Kind* constants (e.g. "recv", "fire", "send", "slot").
// Scanning the whole dir (not just Trace.go) means a Kind* const declared in any
// sibling file under Trace/ is still picked up — the single-file-path guard-blindness
// class (memory: feedback_guards_hardcoding_single_file_break_on_split).
func parseTraceKinds(traceDir string) ([]string, error) {
	entries, err := os.ReadDir(traceDir)
	if err != nil {
		return nil, err
	}
	var kinds []string
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, filepath.Join(traceDir, name), nil, 0)
		if err != nil {
			return nil, err
		}
		for _, decl := range f.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.CONST {
				continue
			}
			for _, spec := range genDecl.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for i, nm := range vs.Names {
					if !strings.HasPrefix(nm.Name, "Kind") {
						continue
					}
					if i >= len(vs.Values) {
						continue
					}
					lit, ok := vs.Values[i].(*ast.BasicLit)
					if !ok || lit.Kind != token.STRING {
						continue
					}
					kinds = append(kinds, strings.Trim(lit.Value, `"`))
				}
			}
		}
	}
	// No sort: os.ReadDir yields filenames in lexical order and go/ast preserves
	// in-file declaration order, so the emitted slice is deterministic across runs.
	if len(kinds) == 0 {
		return nil, fmt.Errorf("no Kind* constants found in %s", traceDir)
	}
	return kinds, nil
}

// writeTraceKinds emits trace-kinds.ts from the parsed kind slice.
func writeTraceKinds(outPath string, kinds []string) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by tools/gen-node-defs — do not edit.`)
	fmt.Fprintln(w, `// Source: Trace/Trace.go Kind* constants. Regenerate with: npm run gen:node-defs`)
	fmt.Fprintln(w)
	fmt.Fprintf(w, "export const TRACE_EVENT_KINDS = [")
	for i, k := range kinds {
		if i > 0 {
			fmt.Fprint(w, ", ")
		}
		fmt.Fprintf(w, "%q", k)
	}
	fmt.Fprintln(w, "] as const;")
	fmt.Fprintln(w)
	fmt.Fprintln(w, `export type TraceEventKind = (typeof TRACE_EVENT_KINDS)[number];`)

	w.Flush()
	return os.WriteFile(outPath, buf.Bytes(), 0644)
}
