// wire-defs.ts emitter: parses wire:"prop,..." tags off specEdge in
// nodes/Wiring/loader.go and emits WIRE_PROPS/WireProps.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

// parseWirePropsFromFile parses wire:"prop,..." tags on fields of specEdge
// in the given Go source file and returns them in declaration order.
func parseWirePropsFromFile(filePath string) ([]wireProp, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filePath, nil, 0)
	if err != nil {
		return nil, err
	}
	var props []wireProp
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok || typeSpec.Name.Name != "specEdge" {
				continue
			}
			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, field := range structType.Fields.List {
				if field.Tag == nil {
					continue
				}
				rawTag := strings.Trim(field.Tag.Value, "`")
				// Extract wire tag value (text after `wire:"` up to the closing quote).
				_, wireVal, hasWire := strings.Cut(rawTag, `wire:"`)
				if !hasWire {
					continue
				}
				wireVal, _, _ = strings.Cut(wireVal, `"`)
				if !strings.HasPrefix(wireVal, "prop,") {
					continue
				}
				// Parse segments: prop, optional|required, tsType:X
				//
				// A malformed prop tag is an ERROR, not a skip. These `continue`s used to be
				// silent: a field tagged wire:"prop,tsType:string" (no optional|required
				// segment) was dropped, the generator still printed "wrote wire-defs.ts
				// (1 entries)" and exited 0, and the prop simply never reached TS. The tag
				// looked correct in review and nothing anywhere said otherwise. If a field
				// says it is a wire prop, either emit it or say why not.
				fieldName := "<anonymous>"
				if len(field.Names) > 0 {
					fieldName = field.Names[0].Name
				}
				segments := strings.Split(wireVal, ",")
				if len(segments) < 3 {
					return nil, fmt.Errorf(
						"specEdge.%s: malformed wire tag %q — want prop,<optional|required>,tsType:<T> (got %d segments, need at least 3)",
						fieldName, wireVal, len(segments))
				}
				if segments[1] != "required" && segments[1] != "optional" {
					return nil, fmt.Errorf(
						"specEdge.%s: wire tag %q has second segment %q — want \"required\" or \"optional\"",
						fieldName, wireVal, segments[1])
				}
				required := segments[1] == "required"
				tsType := ""
				for _, seg := range segments[2:] {
					if after, found := strings.CutPrefix(seg, "tsType:"); found {
						tsType = after
					}
				}
				if tsType == "" {
					return nil, fmt.Errorf(
						"specEdge.%s: wire tag %q has no tsType:<T> segment", fieldName, wireVal)
				}
				// Extract json name.
				jsonName := ""
				_, after, found := strings.Cut(rawTag, `json:"`)
				if found {
					jsonName, _, _ = strings.Cut(after, `"`)
					// Strip omitempty etc.
					jsonName, _, _ = strings.Cut(jsonName, ",")
				}
				if jsonName == "" && len(field.Names) > 0 {
					jsonName = strings.ToLower(field.Names[0].Name[:1]) + field.Names[0].Name[1:]
				}
				props = append(props, wireProp{jsonName: jsonName, tsType: tsType, required: required})
			}
		}
	}
	return props, nil
}

// writeWireDefs emits wire-defs.ts from the parsed wireProp slice.
func writeWireDefs(outPath string, props []wireProp) error {
	var buf bytes.Buffer
	w := bufio.NewWriter(&buf)

	fmt.Fprintln(w, `// GENERATED by: go run ./tools/gen-node-defs (regenerate after editing wire:"..." tags in nodes/Wiring/loader.go)`)
	fmt.Fprintln(w, `// Source: nodes/Wiring/loader.go wire:"prop,..." tags. Do not edit by hand.`)
	fmt.Fprintln(w)
	// Collect non-primitive tsTypes that need importing from ./types.
	primitives := map[string]bool{"string": true, "number": true, "boolean": true}
	seen := map[string]bool{}
	var nonPrim []string
	for _, p := range props {
		t := p.tsType
		if primitives[t] || seen[t] {
			continue
		}
		seen[t] = true
		nonPrim = append(nonPrim, t)
	}
	sort.Strings(nonPrim)
	if len(nonPrim) > 0 {
		fmt.Fprintf(w, "import type { %s } from \"./types\";\n", strings.Join(nonPrim, ", "))
		fmt.Fprintln(w)
	}
	fmt.Fprintln(w, `export interface WirePropDef {`)
	fmt.Fprintln(w, `  tsType: string;`)
	fmt.Fprintln(w, `  required: boolean;`)
	fmt.Fprintln(w, `}`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `export const WIRE_PROPS: Record<string, WirePropDef> = {`)
	for _, p := range props {
		req := "false"
		if p.required {
			req = "true"
		}
		fmt.Fprintf(w, "  %-12s { tsType: %-12s required: %s },\n",
			p.jsonName+":", `"`+p.tsType+`",`, req)
	}
	fmt.Fprintln(w, `};`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `// Derived from WIRE_PROPS — do not hand-edit. Consumed by Edge and EdgeData.`)
	fmt.Fprintln(w, `export type WireProps = {`)
	for _, p := range props {
		opt := "?"
		if p.required {
			opt = ""
		}
		fmt.Fprintf(w, "  %s%s: %s;\n", p.jsonName, opt, p.tsType)
	}
	fmt.Fprintln(w, `};`)

	w.Flush()
	return os.WriteFile(outPath, buf.Bytes(), 0644)
}
