// input_fixture_test.go — CROSS-LANGUAGE byte-level verification that the real TS
// raw-input encoder (encodeRawInput in tools/topology-vscode/src/schema/input-layout.ts)
// and the real Go raw-input decoder (decodeInputRecord in input_codec.go) agree on the
// wire bytes.
//
// Every other input-layout test round-trips WITHIN one language (TS encode→TS decode in
// input-layout.test.ts, Go encode→Go decode in input_codec_test.go). Neither can catch a
// cross-language field-count/offset disagreement: if TS drops N bytes at one offset and Go
// drops N bytes at a DIFFERENT offset, both same-language round-trips still pass while the
// bridge silently misaligns every subsequent field. This test closes that gap by decoding
// TS-produced bytes with the REAL Go decoder and asserting every field.
//
// The fixture (testdata/input_fixture.json) is generated by
// tools/topology-vscode/scripts/gen-input-fixture-src.ts via `npm run gen:input-fixture`
// (see gen-input-fixture.mjs, which bundles that TS file with esbuild and runs it under
// node). It is CHECKED, not trusted: this test also regenerates it live into a temp file
// and byte-diffs it against the committed copy, so a stale fixture — one committed before
// the encoder changed again — fails HERE with a clear message instead of quietly testing
// its own past self. If node is unavailable, the staleness check is skipped (not silently
// passed) and the decode assertions still run against the committed fixture.
package Wiring

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"testing"
)

type fixtureHit struct {
	Kind         string `json:"kind"`
	IsInput      bool   `json:"isInput"`
	NodeRow      int    `json:"nodeRow"`
	PortRow      int    `json:"portRow"`
	EdgeRow      int    `json:"edgeRow"`
	HandholdTerm int    `json:"handholdTerm"`
}

type fixtureEvent struct {
	Kind       string     `json:"kind"`
	X          float64    `json:"x"`
	Y          float64    `json:"y"`
	RectLeft   float64    `json:"rectLeft"`
	RectTop    float64    `json:"rectTop"`
	RectWidth  float64    `json:"rectWidth"`
	RectHeight float64    `json:"rectHeight"`
	Button     int        `json:"button"`
	Ctrl       bool       `json:"ctrl"`
	Shift      bool       `json:"shift"`
	Alt        bool       `json:"alt"`
	Meta       bool       `json:"meta"`
	DeltaX     float64    `json:"deltaX"`
	DeltaY     float64    `json:"deltaY"`
	Fov        float64    `json:"fov"`
	Hit        fixtureHit `json:"hit"`
}

type fixtureRecord struct {
	Event fixtureEvent `json:"event"`
	Hex   string       `json:"hex"`
}

type inputFixture struct {
	Fingerprint string          `json:"fingerprint"`
	Records     []fixtureRecord `json:"records"`
}

// repoRoot derives the repo root from this test file's own path (nodes/Wiring/... is two
// levels below root), so the test works regardless of the invoking cwd.
func repoRootForFixtureTest(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed — cannot locate repo root")
	}
	// nodes/Wiring/input_fixture_test.go -> repo root is two dirs up.
	return filepath.Dir(filepath.Dir(filepath.Dir(thisFile)))
}

func loadFixture(t *testing.T, path string) inputFixture {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading fixture %s: %v", path, err)
	}
	var fx inputFixture
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatalf("parsing fixture %s: %v", path, err)
	}
	return fx
}

// TestInputFixtureFreshness regenerates the fixture live (via node + esbuild bundling the
// REAL TS encoder) into a temp file and byte-diffs it against the committed copy. A stale
// fixture — committed before the TS encoder changed again — fails HERE with a clear
// pointer to the regeneration command, rather than as silent staleness.
func TestInputFixtureFreshness(t *testing.T) {
	if _, err := exec.LookPath("node"); err != nil {
		t.Skip("node not found on PATH — skipping cross-language input-fixture freshness check (decode assertions in TestInputFixtureCrossLanguage still run against the committed fixture)")
	}
	root := repoRootForFixtureTest(t)
	vscodeDir := filepath.Join(root, "tools", "topology-vscode")
	genScript := filepath.Join(vscodeDir, "scripts", "gen-input-fixture.mjs")
	if _, err := os.Stat(genScript); err != nil {
		t.Skip("gen-input-fixture.mjs not found — skipping freshness check")
	}

	tmpOut := filepath.Join(t.TempDir(), "input_fixture.json")
	cmd := exec.Command("node", genScript, tmpOut)
	cmd.Dir = vscodeDir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("regenerating input fixture failed (is `npm install` done in tools/topology-vscode?): %v\n%s", err, out)
	}

	committedPath := filepath.Join(root, "nodes", "Wiring", "testdata", "input_fixture.json")
	committed, err := os.ReadFile(committedPath)
	if err != nil {
		t.Fatalf("reading committed fixture: %v", err)
	}
	fresh, err := os.ReadFile(tmpOut)
	if err != nil {
		t.Fatalf("reading regenerated fixture: %v", err)
	}
	if string(committed) != string(fresh) {
		t.Fatalf("nodes/Wiring/testdata/input_fixture.json is STALE relative to the current TS encoder "+
			"(tools/topology-vscode/src/schema/input-layout.ts). Regenerate with:\n"+
			"  cd tools/topology-vscode && npm run gen:input-fixture\n"+
			"and commit the result.\n\n--- committed ---\n%s\n--- regenerated ---\n%s", committed, fresh)
	}
}

// TestInputFixtureCrossLanguage decodes the TS-encoded fixture bytes with the REAL Go
// decoder (decodeInputRecord) and asserts every field matches what TS encoded — the actual
// cross-language byte-level agreement check. Also asserts the fixture's fingerprint equals
// Go's InputLayoutFingerprint, so a one-sided field/enum change fails here with a clear
// message instead of as mysterious live-editor gesture misbehavior.
func TestInputFixtureCrossLanguage(t *testing.T) {
	root := repoRootForFixtureTest(t)
	committedPath := filepath.Join(root, "nodes", "Wiring", "testdata", "input_fixture.json")
	fx := loadFixture(t, committedPath)

	if fx.Fingerprint != InputLayoutFingerprint {
		t.Fatalf("cross-language fixture fingerprint %q != Go InputLayoutFingerprint %q — "+
			"one side of the TS/Go input-layout changed without the other; this is exactly the "+
			"silent-misalignment bug class this test exists to catch", fx.Fingerprint, InputLayoutFingerprint)
	}
	if len(fx.Records) == 0 {
		t.Fatal("fixture carries zero records — nothing was verified")
	}

	for i, rec := range fx.Records {
		raw, err := hex.DecodeString(rec.Hex)
		if err != nil {
			t.Fatalf("record %d: bad hex in fixture: %v", i, err)
		}
		msg, ok := decodeInputRecord(raw)
		if !ok {
			t.Fatalf("record %d (kind=%s hit=%s): Go decodeInputRecord rejected TS-encoded bytes",
				i, rec.Event.Kind, rec.Event.Hit.Kind)
		}
		if msg.Type != "raw-input" || msg.Event == nil {
			t.Fatalf("record %d: decoded as Type=%q, want raw-input with a non-nil Event", i, msg.Type)
		}
		ev := *msg.Event
		want := rec.Event

		check := func(field string, got, wantV interface{}) {
			if got != wantV {
				t.Errorf("record %d (kind=%s hit=%s) field %s: Go decoded %v, TS encoded %v — "+
					"field misalignment (offset/order/count disagreement between the two REAL codecs)",
					i, want.Kind, want.Hit.Kind, field, got, wantV)
			}
		}

		check("Kind", ev.Kind, want.Kind)
		check("X", ev.X, want.X)
		check("Y", ev.Y, want.Y)
		check("RectLeft", ev.RectLeft, want.RectLeft)
		check("RectTop", ev.RectTop, want.RectTop)
		check("RectWidth", ev.RectWidth, want.RectWidth)
		check("RectHeight", ev.RectHeight, want.RectHeight)
		check("Button", ev.Button, want.Button)
		check("Ctrl", ev.Ctrl, want.Ctrl)
		check("Shift", ev.Shift, want.Shift)
		check("Alt", ev.Alt, want.Alt)
		check("Meta", ev.Meta, want.Meta)
		check("DeltaX", ev.DeltaX, want.DeltaX)
		check("DeltaY", ev.DeltaY, want.DeltaY)
		check("Fov", ev.Fov, want.Fov)
		check("Hit.Kind", ev.Hit.Kind, want.Hit.Kind)
		check("Hit.IsInput", ev.Hit.IsInput, want.Hit.IsInput)
		check("Hit.NodeRow", ev.Hit.NodeRow, want.Hit.NodeRow)
		check("Hit.PortRow", ev.Hit.PortRow, want.Hit.PortRow)
		check("Hit.EdgeRow", ev.Hit.EdgeRow, want.Hit.EdgeRow)
		check("Hit.HandholdTerm", ev.Hit.HandholdTerm, want.Hit.HandholdTerm)
	}
}
