// GENERATED by tools/gen-node-defs — do not edit.
// Source: nodes/<Kind>/SPEC.md ## View width/height fields.
// Regenerate with: cd tools/topology-vscode && npm run gen:node-defs

package Wiring

// kindDim is the render width/height for one node kind, mirroring
// NODE_DEFS[kind].width/height in node-defs.ts.
type kindDim struct{ Width, Height float64 }

// kindDims maps each runtime kind to its render dimensions.
var kindDims = map[string]kindDim{
	"Hold": {Width: 60, Height: 60},
	"HoldFlip": {Width: 36, Height: 36},
	"HoldNewSendOld": {Width: 90, Height: 60},
	"Input": {Width: 80, Height: 60},
	"Pacer": {Width: 60, Height: 60},
	"Pulse": {Width: 90, Height: 60},
	"WindowAndInhibitLeftGate": {Width: 80, Height: 60},
	"WindowAndInhibitRightGate": {Width: 80, Height: 60},
}
