// GENERATED by tools/gen-node-defs — do not edit.
// Source: OVERLAY_FLAG_NAMES in tools/topology-vscode/src/messages.ts.
// Regenerate with: cd tools/topology-vscode && npm run gen:node-defs

package Wiring

import (
	"fmt"

	T "github.com/dtauraso/wirefold/Trace"
)

// overlayState groups the per-toggle overlay-visibility booleans and their
// flip/emit logic. Owned by MoveDispatch (md.ov); the delegators below keep the
// stdin reader's overlayToggles method-expression table binding MoveDispatch.
type overlayState struct {
	sceneToriVisible      bool
	scenePolesVisible     bool
	nodePolesVisible      bool
	selSpherePolesVisible bool
	handholdsVisible      bool
	labelsGlobalVisible   bool
	overlaysVisible       bool
	doubleLinksVisible    bool
}

// setFlag flips *field. Shared body of the uniform Toggle* methods. The RowEvent
// carrying the new value is written by the caller's own goroutine directly (see
// stdin_reader.go's applyUpdate) — this no longer emits through Trace.
func (o *overlayState) setFlag(field *bool) {
	*field = !*field
}

// ToggleSceneTori flips sceneToriVisible.
func (o *overlayState) ToggleSceneTori(tr *T.Trace) {
	o.setFlag(&o.sceneToriVisible)
}

// ToggleScenePoles flips scenePolesVisible.
func (o *overlayState) ToggleScenePoles(tr *T.Trace) {
	o.scenePolesVisible = !o.scenePolesVisible
	tr.Breadcrumb("pole-toggle-go", "scene", "", fmt.Sprintf("visible=%v", o.scenePolesVisible))
}

// ToggleNodePoles flips nodePolesVisible.
func (o *overlayState) ToggleNodePoles(tr *T.Trace) {
	o.nodePolesVisible = !o.nodePolesVisible
	tr.Breadcrumb("pole-toggle-go", "nodes", "", fmt.Sprintf("visible=%v", o.nodePolesVisible))
}

// ToggleSelSpherePoles flips selSpherePolesVisible.
func (o *overlayState) ToggleSelSpherePoles(tr *T.Trace) {
	o.setFlag(&o.selSpherePolesVisible)
}

// ToggleHandholds flips handholdsVisible.
func (o *overlayState) ToggleHandholds(tr *T.Trace) {
	o.setFlag(&o.handholdsVisible)
}

// ToggleLabelsGlobal flips labelsGlobalVisible.
func (o *overlayState) ToggleLabelsGlobal(tr *T.Trace) {
	o.setFlag(&o.labelsGlobalVisible)
}

// ToggleOverlaysVis flips overlaysVisible.
func (o *overlayState) ToggleOverlaysVis(tr *T.Trace) {
	o.setFlag(&o.overlaysVisible)
}

// ToggleDoubleLinks flips doubleLinksVisible.
func (o *overlayState) ToggleDoubleLinks(tr *T.Trace) {
	o.setFlag(&o.doubleLinksVisible)
}

// SetGuideVisibility installs an explicit-visibility snapshot wholesale (the TS
// startup push so settings survive a Go respawn).
func (o *overlayState) SetGuideVisibility(ov overlayState) {
	*o = ov
}

// defaultOverlayState is the startup overlay snapshot used by newMoveDispatch.
func defaultOverlayState() overlayState {
	return overlayState{
		sceneToriVisible:      true,
		scenePolesVisible:     true,
		nodePolesVisible:      true,
		selSpherePolesVisible: true,
		handholdsVisible:      true,
		labelsGlobalVisible:   true,
		overlaysVisible:       true,
	}
}

// Overlay-visibility API — thin delegators to the owned overlayState. The public
// signatures are unchanged (overlayToggles binds these method expressions).
func (md *MoveDispatch) ToggleSceneTori(tr *T.Trace)      { md.ov.ToggleSceneTori(tr) }
func (md *MoveDispatch) ToggleScenePoles(tr *T.Trace)     { md.ov.ToggleScenePoles(tr) }
func (md *MoveDispatch) ToggleNodePoles(tr *T.Trace)      { md.ov.ToggleNodePoles(tr) }
func (md *MoveDispatch) ToggleSelSpherePoles(tr *T.Trace) { md.ov.ToggleSelSpherePoles(tr) }
func (md *MoveDispatch) ToggleHandholds(tr *T.Trace)      { md.ov.ToggleHandholds(tr) }
func (md *MoveDispatch) ToggleLabelsGlobal(tr *T.Trace)   { md.ov.ToggleLabelsGlobal(tr) }
func (md *MoveDispatch) ToggleOverlaysVis(tr *T.Trace)    { md.ov.ToggleOverlaysVis(tr) }
func (md *MoveDispatch) ToggleDoubleLinks(tr *T.Trace)    { md.ov.ToggleDoubleLinks(tr) }

// overlayToggles maps an overlay FLAG name (the attr="toggle" wire name) to the
// MoveDispatch method that flips it.
//
// OVERLAY_TOGGLES_START
var overlayToggles = map[string]func(*MoveDispatch, *T.Trace){
	"tori":           (*MoveDispatch).ToggleSceneTori,
	"scenePoles":     (*MoveDispatch).ToggleScenePoles,
	"nodePoles":      (*MoveDispatch).ToggleNodePoles,
	"selSpherePoles": (*MoveDispatch).ToggleSelSpherePoles,
	"handholds":      (*MoveDispatch).ToggleHandholds,
	"labelsGlobal":   (*MoveDispatch).ToggleLabelsGlobal,
	"overlays":       (*MoveDispatch).ToggleOverlaysVis,
	"doubleLinks":    (*MoveDispatch).ToggleDoubleLinks,
}

// OVERLAY_TOGGLES_END
