// GENERATED by tools/gen-node-defs — do not edit.
// Source: OVERLAY_FLAG_NAMES in tools/topology-vscode/src/messages.ts.
// Regenerate with: cd tools/topology-vscode && npm run gen:node-defs

package Wiring

import (
	"fmt"

	T "github.com/dtauraso/wirefold/Trace"
)

// overlayState groups the per-toggle overlay-visibility booleans and their
// flip/emit logic. Owned by MoveDispatch (md.ov); the delegators below keep the
// stdin reader's overlayToggles method-expression table binding MoveDispatch.
type overlayState struct {
	sceneToriVisible      bool
	scenePolesVisible     bool
	nodePolesVisible      bool
	angleLabelsVisible    bool
	selSpherePolesVisible bool
	handholdsVisible      bool
	labelsGlobalVisible   bool
	badgesGlobalVisible   bool
	overlaysVisible       bool
	doubleLinksVisible    bool
}

// setFlag flips *field and emits the new value via emit. Shared body of the uniform
// (flip-then-emit) Toggle* methods.
func (o *overlayState) setFlag(field *bool, emit func(bool)) {
	*field = !*field
	emit(*field)
}

// ToggleSceneTori flips sceneToriVisible and emits a scene-tori event.
func (o *overlayState) ToggleSceneTori(tr *T.Trace) {
	o.setFlag(&o.sceneToriVisible, tr.SceneTori)
}

// EmitSceneTori emits the current sceneToriVisible without toggling it.
func (o *overlayState) EmitSceneTori(tr *T.Trace) {
	tr.SceneTori(o.sceneToriVisible)
}

// ToggleScenePoles flips scenePolesVisible and emits a scene-poles event.
func (o *overlayState) ToggleScenePoles(tr *T.Trace) {
	o.scenePolesVisible = !o.scenePolesVisible
	tr.Breadcrumb("pole-toggle-go", "scene", "", fmt.Sprintf("visible=%v", o.scenePolesVisible))
	tr.ScenePoles(o.scenePolesVisible)
}

// EmitScenePoles emits the current scenePolesVisible without toggling it.
func (o *overlayState) EmitScenePoles(tr *T.Trace) {
	tr.ScenePoles(o.scenePolesVisible)
}

// ToggleNodePoles flips nodePolesVisible and emits a node-poles event.
func (o *overlayState) ToggleNodePoles(tr *T.Trace) {
	o.nodePolesVisible = !o.nodePolesVisible
	tr.Breadcrumb("pole-toggle-go", "nodes", "", fmt.Sprintf("visible=%v", o.nodePolesVisible))
	tr.NodePoles(o.nodePolesVisible)
}

// EmitNodePoles emits the current nodePolesVisible without toggling it.
func (o *overlayState) EmitNodePoles(tr *T.Trace) {
	tr.NodePoles(o.nodePolesVisible)
}

// ToggleAngleLabels flips angleLabelsVisible and emits a angle-labels event.
func (o *overlayState) ToggleAngleLabels(tr *T.Trace) {
	o.setFlag(&o.angleLabelsVisible, tr.AngleLabels)
}

// EmitAngleLabels emits the current angleLabelsVisible without toggling it.
func (o *overlayState) EmitAngleLabels(tr *T.Trace) {
	tr.AngleLabels(o.angleLabelsVisible)
}

// AngleLabels returns the current angleLabelsVisible.
func (o *overlayState) AngleLabels() bool {
	return o.angleLabelsVisible
}

// ToggleSelSpherePoles flips selSpherePolesVisible and emits a sel-sphere-poles event.
func (o *overlayState) ToggleSelSpherePoles(tr *T.Trace) {
	o.setFlag(&o.selSpherePolesVisible, tr.SelSpherePoles)
}

// EmitSelSpherePoles emits the current selSpherePolesVisible without toggling it.
func (o *overlayState) EmitSelSpherePoles(tr *T.Trace) {
	tr.SelSpherePoles(o.selSpherePolesVisible)
}

// ToggleHandholds flips handholdsVisible and emits a handholds event.
func (o *overlayState) ToggleHandholds(tr *T.Trace) {
	o.setFlag(&o.handholdsVisible, tr.Handholds)
}

// EmitHandholds emits the current handholdsVisible without toggling it.
func (o *overlayState) EmitHandholds(tr *T.Trace) {
	tr.Handholds(o.handholdsVisible)
}

// ToggleLabelsGlobal flips labelsGlobalVisible and emits a labels-global event.
func (o *overlayState) ToggleLabelsGlobal(tr *T.Trace) {
	o.setFlag(&o.labelsGlobalVisible, tr.LabelsGlobal)
}

// EmitLabelsGlobal emits the current labelsGlobalVisible without toggling it.
func (o *overlayState) EmitLabelsGlobal(tr *T.Trace) {
	tr.LabelsGlobal(o.labelsGlobalVisible)
}

// ToggleBadgesGlobal flips badgesGlobalVisible and emits a badges-global event.
func (o *overlayState) ToggleBadgesGlobal(tr *T.Trace) {
	o.setFlag(&o.badgesGlobalVisible, tr.BadgesGlobal)
}

// EmitBadgesGlobal emits the current badgesGlobalVisible without toggling it.
func (o *overlayState) EmitBadgesGlobal(tr *T.Trace) {
	tr.BadgesGlobal(o.badgesGlobalVisible)
}

// ToggleOverlaysVis flips overlaysVisible and emits a overlays-vis event.
func (o *overlayState) ToggleOverlaysVis(tr *T.Trace) {
	o.setFlag(&o.overlaysVisible, tr.OverlaysVis)
}

// EmitOverlaysVis emits the current overlaysVisible without toggling it.
func (o *overlayState) EmitOverlaysVis(tr *T.Trace) {
	tr.OverlaysVis(o.overlaysVisible)
}

// ToggleDoubleLinks flips doubleLinksVisible and emits a double-links event.
func (o *overlayState) ToggleDoubleLinks(tr *T.Trace) {
	o.setFlag(&o.doubleLinksVisible, tr.DoubleLinks)
}

// EmitDoubleLinks emits the current doubleLinksVisible without toggling it.
func (o *overlayState) EmitDoubleLinks(tr *T.Trace) {
	tr.DoubleLinks(o.doubleLinksVisible)
}

// SetGuideVisibility installs an explicit-visibility snapshot wholesale (the TS
// startup push so settings survive a Go respawn) and emits each so the renderer
// reflects them.
func (o *overlayState) SetGuideVisibility(ov overlayState, tr *T.Trace) {
	*o = ov
	o.EmitSceneTori(tr)
	o.EmitScenePoles(tr)
	o.EmitNodePoles(tr)
	o.EmitAngleLabels(tr)
	o.EmitSelSpherePoles(tr)
	o.EmitHandholds(tr)
	o.EmitLabelsGlobal(tr)
	o.EmitBadgesGlobal(tr)
	o.EmitOverlaysVis(tr)
	o.EmitDoubleLinks(tr)
}

// defaultOverlayState is the startup overlay snapshot used by newMoveDispatch.
func defaultOverlayState() overlayState {
	return overlayState{
		sceneToriVisible:      true,
		scenePolesVisible:     true,
		nodePolesVisible:      true,
		angleLabelsVisible:    true,
		selSpherePolesVisible: true,
		handholdsVisible:      true,
		labelsGlobalVisible:   true,
		badgesGlobalVisible:   true,
		overlaysVisible:       true,
	}
}

// Overlay-visibility API — thin delegators to the owned overlayState. The public
// signatures are unchanged (overlayToggles binds these method expressions).
func (md *MoveDispatch) ToggleSceneTori(tr *T.Trace)      { md.ov.ToggleSceneTori(tr) }
func (md *MoveDispatch) EmitSceneTori(tr *T.Trace)        { md.ov.EmitSceneTori(tr) }
func (md *MoveDispatch) ToggleScenePoles(tr *T.Trace)     { md.ov.ToggleScenePoles(tr) }
func (md *MoveDispatch) EmitScenePoles(tr *T.Trace)       { md.ov.EmitScenePoles(tr) }
func (md *MoveDispatch) ToggleNodePoles(tr *T.Trace)      { md.ov.ToggleNodePoles(tr) }
func (md *MoveDispatch) EmitNodePoles(tr *T.Trace)        { md.ov.EmitNodePoles(tr) }
func (md *MoveDispatch) ToggleAngleLabels(tr *T.Trace)    { md.ov.ToggleAngleLabels(tr) }
func (md *MoveDispatch) EmitAngleLabels(tr *T.Trace)      { md.ov.EmitAngleLabels(tr) }
func (md *MoveDispatch) AngleLabels() bool                { return md.ov.AngleLabels() }
func (md *MoveDispatch) ToggleSelSpherePoles(tr *T.Trace) { md.ov.ToggleSelSpherePoles(tr) }
func (md *MoveDispatch) EmitSelSpherePoles(tr *T.Trace)   { md.ov.EmitSelSpherePoles(tr) }
func (md *MoveDispatch) ToggleHandholds(tr *T.Trace)      { md.ov.ToggleHandholds(tr) }
func (md *MoveDispatch) EmitHandholds(tr *T.Trace)        { md.ov.EmitHandholds(tr) }
func (md *MoveDispatch) ToggleLabelsGlobal(tr *T.Trace)   { md.ov.ToggleLabelsGlobal(tr) }
func (md *MoveDispatch) EmitLabelsGlobal(tr *T.Trace)     { md.ov.EmitLabelsGlobal(tr) }
func (md *MoveDispatch) ToggleBadgesGlobal(tr *T.Trace)   { md.ov.ToggleBadgesGlobal(tr) }
func (md *MoveDispatch) EmitBadgesGlobal(tr *T.Trace)     { md.ov.EmitBadgesGlobal(tr) }
func (md *MoveDispatch) ToggleOverlaysVis(tr *T.Trace)    { md.ov.ToggleOverlaysVis(tr) }
func (md *MoveDispatch) EmitOverlaysVis(tr *T.Trace)      { md.ov.EmitOverlaysVis(tr) }
func (md *MoveDispatch) ToggleDoubleLinks(tr *T.Trace)    { md.ov.ToggleDoubleLinks(tr) }
func (md *MoveDispatch) EmitDoubleLinks(tr *T.Trace)      { md.ov.EmitDoubleLinks(tr) }

// SetGuideVisibility delegates the wholesale explicit-visibility push.
func (md *MoveDispatch) SetGuideVisibility(ov overlayState, tr *T.Trace) {
	md.ov.SetGuideVisibility(ov, tr)
}

// overlayToggles maps an overlay FLAG name (the attr="toggle" wire name) to the
// MoveDispatch method that flips it.
//
// OVERLAY_TOGGLES_START
var overlayToggles = map[string]func(*MoveDispatch, *T.Trace){
	"tori":           (*MoveDispatch).ToggleSceneTori,
	"scenePoles":     (*MoveDispatch).ToggleScenePoles,
	"nodePoles":      (*MoveDispatch).ToggleNodePoles,
	"angleLabels":    (*MoveDispatch).ToggleAngleLabels,
	"selSpherePoles": (*MoveDispatch).ToggleSelSpherePoles,
	"handholds":      (*MoveDispatch).ToggleHandholds,
	"labelsGlobal":   (*MoveDispatch).ToggleLabelsGlobal,
	"badgesGlobal":   (*MoveDispatch).ToggleBadgesGlobal,
	"overlays":       (*MoveDispatch).ToggleOverlaysVis,
	"doubleLinks":    (*MoveDispatch).ToggleDoubleLinks,
}

// OVERLAY_TOGGLES_END

// stdinGuideVisPayload holds the explicit-visibility fields for the overlays
// attr="set" op. The json tags are the overlay FLAG vocabulary shared with the TS
// OverlayState.
//
// GUIDEVIS_FIELDS_START
type stdinGuideVisPayload struct {
	Tori           bool `json:"tori"`
	ScenePoles     bool `json:"scenePoles"`
	NodePoles      bool `json:"nodePoles"`
	AngleLabels    bool `json:"angleLabels"`
	SelSpherePoles bool `json:"selSpherePoles"`
	Handholds      bool `json:"handholds"`
	LabelsGlobal   bool `json:"labelsGlobal"`
	BadgesGlobal   bool `json:"badgesGlobal"`
	Overlays       bool `json:"overlays"`
	DoubleLinks    bool `json:"doubleLinks"`
}

// GUIDEVIS_FIELDS_END

// overlayStateFromPayload maps the wire payload onto the named overlayState (no
// positional bool order to get wrong).
func overlayStateFromPayload(s *stdinGuideVisPayload) overlayState {
	return overlayState{
		sceneToriVisible:      s.Tori,
		scenePolesVisible:     s.ScenePoles,
		nodePolesVisible:      s.NodePoles,
		angleLabelsVisible:    s.AngleLabels,
		selSpherePolesVisible: s.SelSpherePoles,
		handholdsVisible:      s.Handholds,
		labelsGlobalVisible:   s.LabelsGlobal,
		badgesGlobalVisible:   s.BadgesGlobal,
		overlaysVisible:       s.Overlays,
		doubleLinksVisible:    s.DoubleLinks,
	}
}
