// GENERATED by tools/gen-node-defs — do not edit.
// Source: Trace/Trace.go Kind* constants. Regenerate with: npm run gen:node-defs

export const TRACE_EVENT_KINDS = ["recv", "fire", "send", "slot", "done", "latency-changed"] as const;

export type TraceEventKind = (typeof TRACE_EVENT_KINDS)[number];
