// GENERATED by tools/gen-node-defs — do not edit.
// Source: Trace/Trace.go Kind* constants. Regenerate with: npm run gen:node-defs

export const TRACE_EVENT_KINDS = ["recv", "fire", "send", "done", "edge-bead", "geometry", "pulse-cancelled", "node-geometry", "arrive", "node-bead", "camera"] as const;

export type TraceEventKind = (typeof TRACE_EVENT_KINDS)[number];
